// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: core/v1/statistic/statistic.proto

package statistic

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatmapReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	StartDate string                 `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string                 `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	IsAc      bool                   `protobuf:"varint,4,opt,name=isAc,proto3" json:"isAc,omitempty"`
	// 组织聚合时可选：缩小到分组 / 分队（个人 userId>0 时忽略）
	GroupId       int64 `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SquadId       int64 `protobuf:"varint,6,opt,name=squadId,proto3" json:"squadId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapReq) Reset() {
	*x = HeatmapReq{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapReq) ProtoMessage() {}

func (x *HeatmapReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapReq.ProtoReflect.Descriptor instead.
func (*HeatmapReq) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{0}
}

func (x *HeatmapReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HeatmapReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *HeatmapReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *HeatmapReq) GetIsAc() bool {
	if x != nil {
		return x.IsAc
	}
	return false
}

func (x *HeatmapReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HeatmapReq) GetSquadId() int64 {
	if x != nil {
		return x.SquadId
	}
	return 0
}

type HeatmapResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int64                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*HeatmapResp_HeatmapItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapResp) Reset() {
	*x = HeatmapResp{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapResp) ProtoMessage() {}

func (x *HeatmapResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapResp.ProtoReflect.Descriptor instead.
func (*HeatmapResp) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{1}
}

func (x *HeatmapResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeatmapResp) GetData() []*HeatmapResp_HeatmapItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type PeriodCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SquadId       int64                  `protobuf:"varint,3,opt,name=squadId,proto3" json:"squadId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodCountReq) Reset() {
	*x = PeriodCountReq{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodCountReq) ProtoMessage() {}

func (x *PeriodCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodCountReq.ProtoReflect.Descriptor instead.
func (*PeriodCountReq) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{2}
}

func (x *PeriodCountReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PeriodCountReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PeriodCountReq) GetSquadId() int64 {
	if x != nil {
		return x.SquadId
	}
	return 0
}

type PeriodCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          *PeriodData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodCountResp) Reset() {
	*x = PeriodCountResp{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodCountResp) ProtoMessage() {}

func (x *PeriodCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodCountResp.ProtoReflect.Descriptor instead.
func (*PeriodCountResp) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{3}
}

func (x *PeriodCountResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PeriodCountResp) GetData() *PeriodData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PeriodData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submit        *SubmitCount           `protobuf:"bytes,1,opt,name=submit,proto3" json:"submit,omitempty"`
	Ac            *AcCount               `protobuf:"bytes,2,opt,name=ac,proto3" json:"ac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodData) Reset() {
	*x = PeriodData{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodData) ProtoMessage() {}

func (x *PeriodData) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodData.ProtoReflect.Descriptor instead.
func (*PeriodData) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{4}
}

func (x *PeriodData) GetSubmit() *SubmitCount {
	if x != nil {
		return x.Submit
	}
	return nil
}

func (x *PeriodData) GetAc() *AcCount {
	if x != nil {
		return x.Ac
	}
	return nil
}

type SubmitCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Today         int64                  `protobuf:"varint,1,opt,name=today,proto3" json:"today,omitempty"`
	ThisWeek      int64                  `protobuf:"varint,2,opt,name=thisWeek,proto3" json:"thisWeek,omitempty"`
	LastWeek      int64                  `protobuf:"varint,3,opt,name=lastWeek,proto3" json:"lastWeek,omitempty"`
	ThisMonth     int64                  `protobuf:"varint,4,opt,name=thisMonth,proto3" json:"thisMonth,omitempty"`
	LastMonth     int64                  `protobuf:"varint,5,opt,name=lastMonth,proto3" json:"lastMonth,omitempty"`
	ThisYear      int64                  `protobuf:"varint,6,opt,name=thisYear,proto3" json:"thisYear,omitempty"`
	LastYear      int64                  `protobuf:"varint,7,opt,name=lastYear,proto3" json:"lastYear,omitempty"`
	Total         int64                  `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCount) Reset() {
	*x = SubmitCount{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCount) ProtoMessage() {}

func (x *SubmitCount) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCount.ProtoReflect.Descriptor instead.
func (*SubmitCount) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitCount) GetToday() int64 {
	if x != nil {
		return x.Today
	}
	return 0
}

func (x *SubmitCount) GetThisWeek() int64 {
	if x != nil {
		return x.ThisWeek
	}
	return 0
}

func (x *SubmitCount) GetLastWeek() int64 {
	if x != nil {
		return x.LastWeek
	}
	return 0
}

func (x *SubmitCount) GetThisMonth() int64 {
	if x != nil {
		return x.ThisMonth
	}
	return 0
}

func (x *SubmitCount) GetLastMonth() int64 {
	if x != nil {
		return x.LastMonth
	}
	return 0
}

func (x *SubmitCount) GetThisYear() int64 {
	if x != nil {
		return x.ThisYear
	}
	return 0
}

func (x *SubmitCount) GetLastYear() int64 {
	if x != nil {
		return x.LastYear
	}
	return 0
}

func (x *SubmitCount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AcCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// today…thisYear：按题去重后的 AC 题数（时段内做过的题）
	Today     int64 `protobuf:"varint,1,opt,name=today,proto3" json:"today,omitempty"`
	ThisWeek  int64 `protobuf:"varint,2,opt,name=thisWeek,proto3" json:"thisWeek,omitempty"`
	LastWeek  int64 `protobuf:"varint,3,opt,name=lastWeek,proto3" json:"lastWeek,omitempty"`
	ThisMonth int64 `protobuf:"varint,4,opt,name=thisMonth,proto3" json:"thisMonth,omitempty"`
	LastMonth int64 `protobuf:"varint,5,opt,name=lastMonth,proto3" json:"lastMonth,omitempty"`
	ThisYear  int64 `protobuf:"varint,6,opt,name=thisYear,proto3" json:"thisYear,omitempty"`
	LastYear  int64 `protobuf:"varint,7,opt,name=lastYear,proto3" json:"lastYear,omitempty"`
	// total：生涯按题去重（累计题数）
	Total int64 `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	// totalRaw：生涯 AC 次数（不去重，同一题多次 AC 全计）
	TotalRaw      int64 `protobuf:"varint,9,opt,name=totalRaw,proto3" json:"totalRaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcCount) Reset() {
	*x = AcCount{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcCount) ProtoMessage() {}

func (x *AcCount) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcCount.ProtoReflect.Descriptor instead.
func (*AcCount) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{6}
}

func (x *AcCount) GetToday() int64 {
	if x != nil {
		return x.Today
	}
	return 0
}

func (x *AcCount) GetThisWeek() int64 {
	if x != nil {
		return x.ThisWeek
	}
	return 0
}

func (x *AcCount) GetLastWeek() int64 {
	if x != nil {
		return x.LastWeek
	}
	return 0
}

func (x *AcCount) GetThisMonth() int64 {
	if x != nil {
		return x.ThisMonth
	}
	return 0
}

func (x *AcCount) GetLastMonth() int64 {
	if x != nil {
		return x.LastMonth
	}
	return 0
}

func (x *AcCount) GetThisYear() int64 {
	if x != nil {
		return x.ThisYear
	}
	return 0
}

func (x *AcCount) GetLastYear() int64 {
	if x != nil {
		return x.LastYear
	}
	return 0
}

func (x *AcCount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AcCount) GetTotalRaw() int64 {
	if x != nil {
		return x.TotalRaw
	}
	return 0
}

type RankReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 开始日期 YYYY-MM-DD（含）
	StartDate string `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	// 结束日期 YYYY-MM-DD（含）
	EndDate string `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
	// submit | ac，默认 submit
	ScoreType string `protobuf:"bytes,3,opt,name=scoreType,proto3" json:"scoreType,omitempty"`
	// 分页，默认 page=1 pageSize=10
	Page     int64 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 分组筛选，0 或不传表示全部（走成员集合过滤）
	GroupId int64 `protobuf:"varint,6,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 分队筛选；优先于 groupId
	SquadId       int64 `protobuf:"varint,7,opt,name=squadId,proto3" json:"squadId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankReq) Reset() {
	*x = RankReq{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankReq) ProtoMessage() {}

func (x *RankReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankReq.ProtoReflect.Descriptor instead.
func (*RankReq) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{7}
}

func (x *RankReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *RankReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *RankReq) GetScoreType() string {
	if x != nil {
		return x.ScoreType
	}
	return ""
}

func (x *RankReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RankReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RankReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RankReq) GetSquadId() int64 {
	if x != nil {
		return x.SquadId
	}
	return 0
}

type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int64                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{8}
}

func (x *RankItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RankItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RankResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*RankItem            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankResp) Reset() {
	*x = RankResp{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResp) ProtoMessage() {}

func (x *RankResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResp.ProtoReflect.Descriptor instead.
func (*RankResp) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{9}
}

func (x *RankResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RankResp) GetData() []*RankItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RankResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HeatmapResp_HeatmapItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapResp_HeatmapItem) Reset() {
	*x = HeatmapResp_HeatmapItem{}
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapResp_HeatmapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapResp_HeatmapItem) ProtoMessage() {}

func (x *HeatmapResp_HeatmapItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_statistic_statistic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapResp_HeatmapItem.ProtoReflect.Descriptor instead.
func (*HeatmapResp_HeatmapItem) Descriptor() ([]byte, []int) {
	return file_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HeatmapResp_HeatmapItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *HeatmapResp_HeatmapItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_core_v1_statistic_statistic_proto protoreflect.FileDescriptor

const file_core_v1_statistic_statistic_proto_rawDesc = "" +
	"\n" +
	"!core/v1/statistic/statistic.proto\x12\x15api.core.v1.statistic\x1a\x1cgoogle/api/annotations.proto\"\xa4\x01\n" +
	"\n" +
	"HeatmapReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tstartDate\x18\x02 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x03 \x01(\tR\aendDate\x12\x12\n" +
	"\x04isAc\x18\x04 \x01(\bR\x04isAc\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x18\n" +
	"\asquadId\x18\x06 \x01(\x03R\asquadId\"\x9e\x01\n" +
	"\vHeatmapResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12B\n" +
	"\x04data\x18\x02 \x03(\v2..api.core.v1.statistic.HeatmapResp.HeatmapItemR\x04data\x1a7\n" +
	"\vHeatmapItem\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\\\n" +
	"\x0ePeriodCountReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\x03R\agroupId\x12\x18\n" +
	"\asquadId\x18\x03 \x01(\x03R\asquadId\"\\\n" +
	"\x0fPeriodCountResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x125\n" +
	"\x04data\x18\x02 \x01(\v2!.api.core.v1.statistic.PeriodDataR\x04data\"x\n" +
	"\n" +
	"PeriodData\x12:\n" +
	"\x06submit\x18\x01 \x01(\v2\".api.core.v1.statistic.SubmitCountR\x06submit\x12.\n" +
	"\x02ac\x18\x02 \x01(\v2\x1e.api.core.v1.statistic.AcCountR\x02ac\"\xe5\x01\n" +
	"\vSubmitCount\x12\x14\n" +
	"\x05today\x18\x01 \x01(\x03R\x05today\x12\x1a\n" +
	"\bthisWeek\x18\x02 \x01(\x03R\bthisWeek\x12\x1a\n" +
	"\blastWeek\x18\x03 \x01(\x03R\blastWeek\x12\x1c\n" +
	"\tthisMonth\x18\x04 \x01(\x03R\tthisMonth\x12\x1c\n" +
	"\tlastMonth\x18\x05 \x01(\x03R\tlastMonth\x12\x1a\n" +
	"\bthisYear\x18\x06 \x01(\x03R\bthisYear\x12\x1a\n" +
	"\blastYear\x18\a \x01(\x03R\blastYear\x12\x14\n" +
	"\x05total\x18\b \x01(\x03R\x05total\"\xfd\x01\n" +
	"\aAcCount\x12\x14\n" +
	"\x05today\x18\x01 \x01(\x03R\x05today\x12\x1a\n" +
	"\bthisWeek\x18\x02 \x01(\x03R\bthisWeek\x12\x1a\n" +
	"\blastWeek\x18\x03 \x01(\x03R\blastWeek\x12\x1c\n" +
	"\tthisMonth\x18\x04 \x01(\x03R\tthisMonth\x12\x1c\n" +
	"\tlastMonth\x18\x05 \x01(\x03R\tlastMonth\x12\x1a\n" +
	"\bthisYear\x18\x06 \x01(\x03R\bthisYear\x12\x1a\n" +
	"\blastYear\x18\a \x01(\x03R\blastYear\x12\x14\n" +
	"\x05total\x18\b \x01(\x03R\x05total\x12\x1a\n" +
	"\btotalRaw\x18\t \x01(\x03R\btotalRaw\"\xc3\x01\n" +
	"\aRankReq\x12\x1c\n" +
	"\tstartDate\x18\x01 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x02 \x01(\tR\aendDate\x12\x1c\n" +
	"\tscoreType\x18\x03 \x01(\tR\tscoreType\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x05 \x01(\x03R\bpageSize\x12\x18\n" +
	"\agroupId\x18\x06 \x01(\x03R\agroupId\x12\x18\n" +
	"\asquadId\x18\a \x01(\x03R\asquadId\"`\n" +
	"\bRankItem\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x03R\x04rank\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\"i\n" +
	"\bRankResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x123\n" +
	"\x04data\x18\x02 \x03(\v2\x1f.api.core.v1.statistic.RankItemR\x04data\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total2\xec\x02\n" +
	"\tStatistic\x12t\n" +
	"\aHeatmap\x12!.api.core.v1.statistic.HeatmapReq\x1a\".api.core.v1.statistic.HeatmapResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/core/statistic/heatmap\x12\x7f\n" +
	"\vPeriodCount\x12%.api.core.v1.statistic.PeriodCountReq\x1a&.api.core.v1.statistic.PeriodCountResp\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/core/statistic/period\x12h\n" +
	"\x04Rank\x12\x1e.api.core.v1.statistic.RankReq\x1a\x1f.api.core.v1.statistic.RankResp\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/core/statistic/rankBD\n" +
	"\x15api.core.v1.statisticP\x01Z)cwxu-algo/api/core/v1/statistic;statisticb\x06proto3"

var (
	file_core_v1_statistic_statistic_proto_rawDescOnce sync.Once
	file_core_v1_statistic_statistic_proto_rawDescData []byte
)

func file_core_v1_statistic_statistic_proto_rawDescGZIP() []byte {
	file_core_v1_statistic_statistic_proto_rawDescOnce.Do(func() {
		file_core_v1_statistic_statistic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_statistic_statistic_proto_rawDesc), len(file_core_v1_statistic_statistic_proto_rawDesc)))
	})
	return file_core_v1_statistic_statistic_proto_rawDescData
}

var file_core_v1_statistic_statistic_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_v1_statistic_statistic_proto_goTypes = []any{
	(*HeatmapReq)(nil),              // 0: api.core.v1.statistic.HeatmapReq
	(*HeatmapResp)(nil),             // 1: api.core.v1.statistic.HeatmapResp
	(*PeriodCountReq)(nil),          // 2: api.core.v1.statistic.PeriodCountReq
	(*PeriodCountResp)(nil),         // 3: api.core.v1.statistic.PeriodCountResp
	(*PeriodData)(nil),              // 4: api.core.v1.statistic.PeriodData
	(*SubmitCount)(nil),             // 5: api.core.v1.statistic.SubmitCount
	(*AcCount)(nil),                 // 6: api.core.v1.statistic.AcCount
	(*RankReq)(nil),                 // 7: api.core.v1.statistic.RankReq
	(*RankItem)(nil),                // 8: api.core.v1.statistic.RankItem
	(*RankResp)(nil),                // 9: api.core.v1.statistic.RankResp
	(*HeatmapResp_HeatmapItem)(nil), // 10: api.core.v1.statistic.HeatmapResp.HeatmapItem
}
var file_core_v1_statistic_statistic_proto_depIdxs = []int32{
	10, // 0: api.core.v1.statistic.HeatmapResp.data:type_name -> api.core.v1.statistic.HeatmapResp.HeatmapItem
	4,  // 1: api.core.v1.statistic.PeriodCountResp.data:type_name -> api.core.v1.statistic.PeriodData
	5,  // 2: api.core.v1.statistic.PeriodData.submit:type_name -> api.core.v1.statistic.SubmitCount
	6,  // 3: api.core.v1.statistic.PeriodData.ac:type_name -> api.core.v1.statistic.AcCount
	8,  // 4: api.core.v1.statistic.RankResp.data:type_name -> api.core.v1.statistic.RankItem
	0,  // 5: api.core.v1.statistic.Statistic.Heatmap:input_type -> api.core.v1.statistic.HeatmapReq
	2,  // 6: api.core.v1.statistic.Statistic.PeriodCount:input_type -> api.core.v1.statistic.PeriodCountReq
	7,  // 7: api.core.v1.statistic.Statistic.Rank:input_type -> api.core.v1.statistic.RankReq
	1,  // 8: api.core.v1.statistic.Statistic.Heatmap:output_type -> api.core.v1.statistic.HeatmapResp
	3,  // 9: api.core.v1.statistic.Statistic.PeriodCount:output_type -> api.core.v1.statistic.PeriodCountResp
	9,  // 10: api.core.v1.statistic.Statistic.Rank:output_type -> api.core.v1.statistic.RankResp
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_core_v1_statistic_statistic_proto_init() }
func file_core_v1_statistic_statistic_proto_init() {
	if File_core_v1_statistic_statistic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_statistic_statistic_proto_rawDesc), len(file_core_v1_statistic_statistic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_statistic_statistic_proto_goTypes,
		DependencyIndexes: file_core_v1_statistic_statistic_proto_depIdxs,
		MessageInfos:      file_core_v1_statistic_statistic_proto_msgTypes,
	}.Build()
	File_core_v1_statistic_statistic_proto = out.File
	file_core_v1_statistic_statistic_proto_goTypes = nil
	file_core_v1_statistic_statistic_proto_depIdxs = nil
}
