// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: core/v1/problem/problem.proto

package problem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Problem_List_FullMethodName                 = "/api.core.v1.problem.Problem/List"
	Problem_ListTags_FullMethodName             = "/api.core.v1.problem.Problem/ListTags"
	Problem_Hot_FullMethodName                  = "/api.core.v1.problem.Problem/Hot"
	Problem_Get_FullMethodName                  = "/api.core.v1.problem.Problem/Get"
	Problem_RelatedContests_FullMethodName      = "/api.core.v1.problem.Problem/RelatedContests"
	Problem_ListSubmissions_FullMethodName      = "/api.core.v1.problem.Problem/ListSubmissions"
	Problem_FollowingStatus_FullMethodName      = "/api.core.v1.problem.Problem/FollowingStatus"
	Problem_UserProfile_FullMethodName          = "/api.core.v1.problem.Problem/UserProfile"
	Problem_Progress_FullMethodName             = "/api.core.v1.problem.Problem/Progress"
	Problem_Backfill_FullMethodName             = "/api.core.v1.problem.Problem/Backfill"
	Problem_EmergencyStop_FullMethodName        = "/api.core.v1.problem.Problem/EmergencyStop"
	Problem_ResetAll_FullMethodName             = "/api.core.v1.problem.Problem/ResetAll"
	Problem_Resume_FullMethodName               = "/api.core.v1.problem.Problem/Resume"
	Problem_RetryFailed_FullMethodName          = "/api.core.v1.problem.Problem/RetryFailed"
	Problem_ClearRecentFailed_FullMethodName    = "/api.core.v1.problem.Problem/ClearRecentFailed"
	Problem_ClearNowCoderContent_FullMethodName = "/api.core.v1.problem.Problem/ClearNowCoderContent"
	Problem_ToggleAnalyze_FullMethodName        = "/api.core.v1.problem.Problem/ToggleAnalyze"
	Problem_ToggleFetch_FullMethodName          = "/api.core.v1.problem.Problem/ToggleFetch"
	Problem_ResetQueues_FullMethodName          = "/api.core.v1.problem.Problem/ResetQueues"
	Problem_AdminUpdate_FullMethodName          = "/api.core.v1.problem.Problem/AdminUpdate"
	Problem_ProposeEdit_FullMethodName          = "/api.core.v1.problem.Problem/ProposeEdit"
	Problem_ListEditRequests_FullMethodName     = "/api.core.v1.problem.Problem/ListEditRequests"
	Problem_ReviewEdit_FullMethodName           = "/api.core.v1.problem.Problem/ReviewEdit"
	Problem_MyPendingEdit_FullMethodName        = "/api.core.v1.problem.Problem/MyPendingEdit"
)

// ProblemClient is the client API for Problem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProblemClient interface {
	List(ctx context.Context, in *ListProblemReq, opts ...grpc.CallOption) (*ListProblemRes, error)
	// 标签聚合（名称 + 题量），供筛选器选择
	ListTags(ctx context.Context, in *ListTagsReq, opts ...grpc.CallOption) (*ListTagsRes, error)
	// 全站热题：近 N 天按提交次数 / 做题人数 / AC 次数综合热度排序
	Hot(ctx context.Context, in *HotProblemReq, opts ...grpc.CallOption) (*HotProblemRes, error)
	Get(ctx context.Context, in *GetProblemReq, opts ...grpc.CallOption) (*GetProblemRes, error)
	// 本题出现过的比赛（contest_problems 反查，全平台）
	RelatedContests(ctx context.Context, in *RelatedContestsReq, opts ...grpc.CallOption) (*RelatedContestsRes, error)
	ListSubmissions(ctx context.Context, in *ListSubmissionsReq, opts ...grpc.CallOption) (*ListSubmissionsRes, error)
	// 关注用户对本题状态（不受组织域限制；需登录）
	FollowingStatus(ctx context.Context, in *FollowingStatusReq, opts ...grpc.CallOption) (*FollowingStatusRes, error)
	UserProfile(ctx context.Context, in *UserProfileReq, opts ...grpc.CallOption) (*UserProfileRes, error)
	Progress(ctx context.Context, in *ProgressReq, opts ...grpc.CallOption) (*ProgressRes, error)
	Backfill(ctx context.Context, in *BackfillReq, opts ...grpc.CallOption) (*BackfillRes, error)
	// 紧急停止：暂停 AI 并清空分析队列（兼容）
	EmergencyStop(ctx context.Context, in *EmergencyStopReq, opts ...grpc.CallOption) (*EmergencyStopRes, error)
	// 全部重置：清空 AI 标签，保留题面，可选重新入队分析
	ResetAll(ctx context.Context, in *ResetAllReq, opts ...grpc.CallOption) (*ResetAllRes, error)
	// 恢复 AI（兼容）
	Resume(ctx context.Context, in *ResumeReq, opts ...grpc.CallOption) (*ResumeRes, error)
	// 重试错误队列：默认仅 FAILED；include_permanent=true 时含可恢复的 FAILED_PERM
	RetryFailed(ctx context.Context, in *RetryFailedReq, opts ...grpc.CallOption) (*RetryFailedRes, error)
	// 清空近期失败：近 6 月 FAILED → FAILED_PERM，停止自动退避重试
	ClearRecentFailed(ctx context.Context, in *ClearRecentFailedReq, opts ...grpc.CallOption) (*ClearRecentFailedRes, error)
	// 清空牛客题面并强制重爬：只清 content_md，保留 tags / solutions_meta
	ClearNowCoderContent(ctx context.Context, in *ClearNowCoderContentReq, opts ...grpc.CallOption) (*ClearNowCoderContentRes, error)
	// 暂停/恢复 AI 分析（仅停消费，不清空队列）
	ToggleAnalyze(ctx context.Context, in *TogglePipelineReq, opts ...grpc.CallOption) (*TogglePipelineRes, error)
	// 暂停/恢复题面爬取（仅停消费，不清空队列）
	ToggleFetch(ctx context.Context, in *TogglePipelineReq, opts ...grpc.CallOption) (*TogglePipelineRes, error)
	// 重置 MQ 队列：purge 爬取/分析队列，再按 DB 待爬取/待分析重灌（低优先级）
	ResetQueues(ctx context.Context, in *ResetQueuesReq, opts ...grpc.CallOption) (*ResetQueuesRes, error)
	// 站点管理员：直接修改标签/题面（无需审核）
	AdminUpdate(ctx context.Context, in *AdminUpdateProblemReq, opts ...grpc.CallOption) (*AdminUpdateProblemRes, error)
	// 登录用户：提交标签/题面修改申请（站点管理员审核）
	ProposeEdit(ctx context.Context, in *ProposeProblemEditReq, opts ...grpc.CallOption) (*ProposeProblemEditRes, error)
	// 站点管理员：审核申请列表
	ListEditRequests(ctx context.Context, in *ListProblemEditReq, opts ...grpc.CallOption) (*ListProblemEditRes, error)
	// 站点管理员：通过/驳回申请
	ReviewEdit(ctx context.Context, in *ReviewProblemEditReq, opts ...grpc.CallOption) (*ReviewProblemEditRes, error)
	// 当前用户对该题的待审申请（详情页提示）
	MyPendingEdit(ctx context.Context, in *MyPendingEditReq, opts ...grpc.CallOption) (*MyPendingEditRes, error)
}

type problemClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemClient(cc grpc.ClientConnInterface) ProblemClient {
	return &problemClient{cc}
}

func (c *problemClient) List(ctx context.Context, in *ListProblemReq, opts ...grpc.CallOption) (*ListProblemRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProblemRes)
	err := c.cc.Invoke(ctx, Problem_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ListTags(ctx context.Context, in *ListTagsReq, opts ...grpc.CallOption) (*ListTagsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsRes)
	err := c.cc.Invoke(ctx, Problem_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Hot(ctx context.Context, in *HotProblemReq, opts ...grpc.CallOption) (*HotProblemRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotProblemRes)
	err := c.cc.Invoke(ctx, Problem_Hot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Get(ctx context.Context, in *GetProblemReq, opts ...grpc.CallOption) (*GetProblemRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemRes)
	err := c.cc.Invoke(ctx, Problem_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) RelatedContests(ctx context.Context, in *RelatedContestsReq, opts ...grpc.CallOption) (*RelatedContestsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelatedContestsRes)
	err := c.cc.Invoke(ctx, Problem_RelatedContests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ListSubmissions(ctx context.Context, in *ListSubmissionsReq, opts ...grpc.CallOption) (*ListSubmissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubmissionsRes)
	err := c.cc.Invoke(ctx, Problem_ListSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) FollowingStatus(ctx context.Context, in *FollowingStatusReq, opts ...grpc.CallOption) (*FollowingStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowingStatusRes)
	err := c.cc.Invoke(ctx, Problem_FollowingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) UserProfile(ctx context.Context, in *UserProfileReq, opts ...grpc.CallOption) (*UserProfileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileRes)
	err := c.cc.Invoke(ctx, Problem_UserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Progress(ctx context.Context, in *ProgressReq, opts ...grpc.CallOption) (*ProgressRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressRes)
	err := c.cc.Invoke(ctx, Problem_Progress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Backfill(ctx context.Context, in *BackfillReq, opts ...grpc.CallOption) (*BackfillRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackfillRes)
	err := c.cc.Invoke(ctx, Problem_Backfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) EmergencyStop(ctx context.Context, in *EmergencyStopReq, opts ...grpc.CallOption) (*EmergencyStopRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmergencyStopRes)
	err := c.cc.Invoke(ctx, Problem_EmergencyStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ResetAll(ctx context.Context, in *ResetAllReq, opts ...grpc.CallOption) (*ResetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetAllRes)
	err := c.cc.Invoke(ctx, Problem_ResetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Resume(ctx context.Context, in *ResumeReq, opts ...grpc.CallOption) (*ResumeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRes)
	err := c.cc.Invoke(ctx, Problem_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) RetryFailed(ctx context.Context, in *RetryFailedReq, opts ...grpc.CallOption) (*RetryFailedRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryFailedRes)
	err := c.cc.Invoke(ctx, Problem_RetryFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ClearRecentFailed(ctx context.Context, in *ClearRecentFailedReq, opts ...grpc.CallOption) (*ClearRecentFailedRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearRecentFailedRes)
	err := c.cc.Invoke(ctx, Problem_ClearRecentFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ClearNowCoderContent(ctx context.Context, in *ClearNowCoderContentReq, opts ...grpc.CallOption) (*ClearNowCoderContentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearNowCoderContentRes)
	err := c.cc.Invoke(ctx, Problem_ClearNowCoderContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ToggleAnalyze(ctx context.Context, in *TogglePipelineReq, opts ...grpc.CallOption) (*TogglePipelineRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TogglePipelineRes)
	err := c.cc.Invoke(ctx, Problem_ToggleAnalyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ToggleFetch(ctx context.Context, in *TogglePipelineReq, opts ...grpc.CallOption) (*TogglePipelineRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TogglePipelineRes)
	err := c.cc.Invoke(ctx, Problem_ToggleFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ResetQueues(ctx context.Context, in *ResetQueuesReq, opts ...grpc.CallOption) (*ResetQueuesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetQueuesRes)
	err := c.cc.Invoke(ctx, Problem_ResetQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) AdminUpdate(ctx context.Context, in *AdminUpdateProblemReq, opts ...grpc.CallOption) (*AdminUpdateProblemRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateProblemRes)
	err := c.cc.Invoke(ctx, Problem_AdminUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ProposeEdit(ctx context.Context, in *ProposeProblemEditReq, opts ...grpc.CallOption) (*ProposeProblemEditRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeProblemEditRes)
	err := c.cc.Invoke(ctx, Problem_ProposeEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ListEditRequests(ctx context.Context, in *ListProblemEditReq, opts ...grpc.CallOption) (*ListProblemEditRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProblemEditRes)
	err := c.cc.Invoke(ctx, Problem_ListEditRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ReviewEdit(ctx context.Context, in *ReviewProblemEditReq, opts ...grpc.CallOption) (*ReviewProblemEditRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewProblemEditRes)
	err := c.cc.Invoke(ctx, Problem_ReviewEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) MyPendingEdit(ctx context.Context, in *MyPendingEditReq, opts ...grpc.CallOption) (*MyPendingEditRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyPendingEditRes)
	err := c.cc.Invoke(ctx, Problem_MyPendingEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServer is the server API for Problem service.
// All implementations must embed UnimplementedProblemServer
// for forward compatibility.
type ProblemServer interface {
	List(context.Context, *ListProblemReq) (*ListProblemRes, error)
	// 标签聚合（名称 + 题量），供筛选器选择
	ListTags(context.Context, *ListTagsReq) (*ListTagsRes, error)
	// 全站热题：近 N 天按提交次数 / 做题人数 / AC 次数综合热度排序
	Hot(context.Context, *HotProblemReq) (*HotProblemRes, error)
	Get(context.Context, *GetProblemReq) (*GetProblemRes, error)
	// 本题出现过的比赛（contest_problems 反查，全平台）
	RelatedContests(context.Context, *RelatedContestsReq) (*RelatedContestsRes, error)
	ListSubmissions(context.Context, *ListSubmissionsReq) (*ListSubmissionsRes, error)
	// 关注用户对本题状态（不受组织域限制；需登录）
	FollowingStatus(context.Context, *FollowingStatusReq) (*FollowingStatusRes, error)
	UserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error)
	Progress(context.Context, *ProgressReq) (*ProgressRes, error)
	Backfill(context.Context, *BackfillReq) (*BackfillRes, error)
	// 紧急停止：暂停 AI 并清空分析队列（兼容）
	EmergencyStop(context.Context, *EmergencyStopReq) (*EmergencyStopRes, error)
	// 全部重置：清空 AI 标签，保留题面，可选重新入队分析
	ResetAll(context.Context, *ResetAllReq) (*ResetAllRes, error)
	// 恢复 AI（兼容）
	Resume(context.Context, *ResumeReq) (*ResumeRes, error)
	// 重试错误队列：默认仅 FAILED；include_permanent=true 时含可恢复的 FAILED_PERM
	RetryFailed(context.Context, *RetryFailedReq) (*RetryFailedRes, error)
	// 清空近期失败：近 6 月 FAILED → FAILED_PERM，停止自动退避重试
	ClearRecentFailed(context.Context, *ClearRecentFailedReq) (*ClearRecentFailedRes, error)
	// 清空牛客题面并强制重爬：只清 content_md，保留 tags / solutions_meta
	ClearNowCoderContent(context.Context, *ClearNowCoderContentReq) (*ClearNowCoderContentRes, error)
	// 暂停/恢复 AI 分析（仅停消费，不清空队列）
	ToggleAnalyze(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error)
	// 暂停/恢复题面爬取（仅停消费，不清空队列）
	ToggleFetch(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error)
	// 重置 MQ 队列：purge 爬取/分析队列，再按 DB 待爬取/待分析重灌（低优先级）
	ResetQueues(context.Context, *ResetQueuesReq) (*ResetQueuesRes, error)
	// 站点管理员：直接修改标签/题面（无需审核）
	AdminUpdate(context.Context, *AdminUpdateProblemReq) (*AdminUpdateProblemRes, error)
	// 登录用户：提交标签/题面修改申请（站点管理员审核）
	ProposeEdit(context.Context, *ProposeProblemEditReq) (*ProposeProblemEditRes, error)
	// 站点管理员：审核申请列表
	ListEditRequests(context.Context, *ListProblemEditReq) (*ListProblemEditRes, error)
	// 站点管理员：通过/驳回申请
	ReviewEdit(context.Context, *ReviewProblemEditReq) (*ReviewProblemEditRes, error)
	// 当前用户对该题的待审申请（详情页提示）
	MyPendingEdit(context.Context, *MyPendingEditReq) (*MyPendingEditRes, error)
	mustEmbedUnimplementedProblemServer()
}

// UnimplementedProblemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProblemServer struct{}

func (UnimplementedProblemServer) List(context.Context, *ListProblemReq) (*ListProblemRes, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProblemServer) ListTags(context.Context, *ListTagsReq) (*ListTagsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedProblemServer) Hot(context.Context, *HotProblemReq) (*HotProblemRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Hot not implemented")
}
func (UnimplementedProblemServer) Get(context.Context, *GetProblemReq) (*GetProblemRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProblemServer) RelatedContests(context.Context, *RelatedContestsReq) (*RelatedContestsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RelatedContests not implemented")
}
func (UnimplementedProblemServer) ListSubmissions(context.Context, *ListSubmissionsReq) (*ListSubmissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubmissions not implemented")
}
func (UnimplementedProblemServer) FollowingStatus(context.Context, *FollowingStatusReq) (*FollowingStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowingStatus not implemented")
}
func (UnimplementedProblemServer) UserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UserProfile not implemented")
}
func (UnimplementedProblemServer) Progress(context.Context, *ProgressReq) (*ProgressRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Progress not implemented")
}
func (UnimplementedProblemServer) Backfill(context.Context, *BackfillReq) (*BackfillRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Backfill not implemented")
}
func (UnimplementedProblemServer) EmergencyStop(context.Context, *EmergencyStopReq) (*EmergencyStopRes, error) {
	return nil, status.Error(codes.Unimplemented, "method EmergencyStop not implemented")
}
func (UnimplementedProblemServer) ResetAll(context.Context, *ResetAllReq) (*ResetAllRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetAll not implemented")
}
func (UnimplementedProblemServer) Resume(context.Context, *ResumeReq) (*ResumeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedProblemServer) RetryFailed(context.Context, *RetryFailedReq) (*RetryFailedRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryFailed not implemented")
}
func (UnimplementedProblemServer) ClearRecentFailed(context.Context, *ClearRecentFailedReq) (*ClearRecentFailedRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearRecentFailed not implemented")
}
func (UnimplementedProblemServer) ClearNowCoderContent(context.Context, *ClearNowCoderContentReq) (*ClearNowCoderContentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearNowCoderContent not implemented")
}
func (UnimplementedProblemServer) ToggleAnalyze(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleAnalyze not implemented")
}
func (UnimplementedProblemServer) ToggleFetch(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleFetch not implemented")
}
func (UnimplementedProblemServer) ResetQueues(context.Context, *ResetQueuesReq) (*ResetQueuesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetQueues not implemented")
}
func (UnimplementedProblemServer) AdminUpdate(context.Context, *AdminUpdateProblemReq) (*AdminUpdateProblemRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdate not implemented")
}
func (UnimplementedProblemServer) ProposeEdit(context.Context, *ProposeProblemEditReq) (*ProposeProblemEditRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeEdit not implemented")
}
func (UnimplementedProblemServer) ListEditRequests(context.Context, *ListProblemEditReq) (*ListProblemEditRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEditRequests not implemented")
}
func (UnimplementedProblemServer) ReviewEdit(context.Context, *ReviewProblemEditReq) (*ReviewProblemEditRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewEdit not implemented")
}
func (UnimplementedProblemServer) MyPendingEdit(context.Context, *MyPendingEditReq) (*MyPendingEditRes, error) {
	return nil, status.Error(codes.Unimplemented, "method MyPendingEdit not implemented")
}
func (UnimplementedProblemServer) mustEmbedUnimplementedProblemServer() {}
func (UnimplementedProblemServer) testEmbeddedByValue()                 {}

// UnsafeProblemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemServer will
// result in compilation errors.
type UnsafeProblemServer interface {
	mustEmbedUnimplementedProblemServer()
}

func RegisterProblemServer(s grpc.ServiceRegistrar, srv ProblemServer) {
	// If the following call panics, it indicates UnimplementedProblemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Problem_ServiceDesc, srv)
}

func _Problem_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).List(ctx, req.(*ListProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ListTags(ctx, req.(*ListTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Hot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Hot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Hot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Hot(ctx, req.(*HotProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Get(ctx, req.(*GetProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_RelatedContests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelatedContestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).RelatedContests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_RelatedContests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).RelatedContests(ctx, req.(*RelatedContestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ListSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubmissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ListSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ListSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ListSubmissions(ctx, req.(*ListSubmissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_FollowingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowingStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).FollowingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_FollowingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).FollowingStatus(ctx, req.(*FollowingStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_UserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).UserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_UserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).UserProfile(ctx, req.(*UserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Progress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Progress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Progress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Progress(ctx, req.(*ProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Backfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Backfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Backfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Backfill(ctx, req.(*BackfillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_EmergencyStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyStopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).EmergencyStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_EmergencyStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).EmergencyStop(ctx, req.(*EmergencyStopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ResetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ResetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ResetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ResetAll(ctx, req.(*ResetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Resume(ctx, req.(*ResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_RetryFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFailedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).RetryFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_RetryFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).RetryFailed(ctx, req.(*RetryFailedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ClearRecentFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRecentFailedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ClearRecentFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ClearRecentFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ClearRecentFailed(ctx, req.(*ClearRecentFailedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ClearNowCoderContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearNowCoderContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ClearNowCoderContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ClearNowCoderContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ClearNowCoderContent(ctx, req.(*ClearNowCoderContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ToggleAnalyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePipelineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ToggleAnalyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ToggleAnalyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ToggleAnalyze(ctx, req.(*TogglePipelineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ToggleFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePipelineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ToggleFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ToggleFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ToggleFetch(ctx, req.(*TogglePipelineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ResetQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetQueuesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ResetQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ResetQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ResetQueues(ctx, req.(*ResetQueuesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_AdminUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).AdminUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_AdminUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).AdminUpdate(ctx, req.(*AdminUpdateProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ProposeEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeProblemEditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ProposeEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ProposeEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ProposeEdit(ctx, req.(*ProposeProblemEditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ListEditRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemEditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ListEditRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ListEditRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ListEditRequests(ctx, req.(*ListProblemEditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ReviewEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewProblemEditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ReviewEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ReviewEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ReviewEdit(ctx, req.(*ReviewProblemEditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_MyPendingEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyPendingEditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).MyPendingEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_MyPendingEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).MyPendingEdit(ctx, req.(*MyPendingEditReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Problem_ServiceDesc is the grpc.ServiceDesc for Problem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Problem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.core.v1.problem.Problem",
	HandlerType: (*ProblemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Problem_List_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Problem_ListTags_Handler,
		},
		{
			MethodName: "Hot",
			Handler:    _Problem_Hot_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Problem_Get_Handler,
		},
		{
			MethodName: "RelatedContests",
			Handler:    _Problem_RelatedContests_Handler,
		},
		{
			MethodName: "ListSubmissions",
			Handler:    _Problem_ListSubmissions_Handler,
		},
		{
			MethodName: "FollowingStatus",
			Handler:    _Problem_FollowingStatus_Handler,
		},
		{
			MethodName: "UserProfile",
			Handler:    _Problem_UserProfile_Handler,
		},
		{
			MethodName: "Progress",
			Handler:    _Problem_Progress_Handler,
		},
		{
			MethodName: "Backfill",
			Handler:    _Problem_Backfill_Handler,
		},
		{
			MethodName: "EmergencyStop",
			Handler:    _Problem_EmergencyStop_Handler,
		},
		{
			MethodName: "ResetAll",
			Handler:    _Problem_ResetAll_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Problem_Resume_Handler,
		},
		{
			MethodName: "RetryFailed",
			Handler:    _Problem_RetryFailed_Handler,
		},
		{
			MethodName: "ClearRecentFailed",
			Handler:    _Problem_ClearRecentFailed_Handler,
		},
		{
			MethodName: "ClearNowCoderContent",
			Handler:    _Problem_ClearNowCoderContent_Handler,
		},
		{
			MethodName: "ToggleAnalyze",
			Handler:    _Problem_ToggleAnalyze_Handler,
		},
		{
			MethodName: "ToggleFetch",
			Handler:    _Problem_ToggleFetch_Handler,
		},
		{
			MethodName: "ResetQueues",
			Handler:    _Problem_ResetQueues_Handler,
		},
		{
			MethodName: "AdminUpdate",
			Handler:    _Problem_AdminUpdate_Handler,
		},
		{
			MethodName: "ProposeEdit",
			Handler:    _Problem_ProposeEdit_Handler,
		},
		{
			MethodName: "ListEditRequests",
			Handler:    _Problem_ListEditRequests_Handler,
		},
		{
			MethodName: "ReviewEdit",
			Handler:    _Problem_ReviewEdit_Handler,
		},
		{
			MethodName: "MyPendingEdit",
			Handler:    _Problem_MyPendingEdit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/problem/problem.proto",
}
