// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: core/v1/problem/problem.proto

package problem

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProblemAdminUpdate = "/api.core.v1.problem.Problem/AdminUpdate"
const OperationProblemBackfill = "/api.core.v1.problem.Problem/Backfill"
const OperationProblemClearNowCoderContent = "/api.core.v1.problem.Problem/ClearNowCoderContent"
const OperationProblemClearRecentFailed = "/api.core.v1.problem.Problem/ClearRecentFailed"
const OperationProblemEmergencyStop = "/api.core.v1.problem.Problem/EmergencyStop"
const OperationProblemFollowingStatus = "/api.core.v1.problem.Problem/FollowingStatus"
const OperationProblemGet = "/api.core.v1.problem.Problem/Get"
const OperationProblemHot = "/api.core.v1.problem.Problem/Hot"
const OperationProblemList = "/api.core.v1.problem.Problem/List"
const OperationProblemListEditRequests = "/api.core.v1.problem.Problem/ListEditRequests"
const OperationProblemListSubmissions = "/api.core.v1.problem.Problem/ListSubmissions"
const OperationProblemListTags = "/api.core.v1.problem.Problem/ListTags"
const OperationProblemMyPendingEdit = "/api.core.v1.problem.Problem/MyPendingEdit"
const OperationProblemProgress = "/api.core.v1.problem.Problem/Progress"
const OperationProblemProposeEdit = "/api.core.v1.problem.Problem/ProposeEdit"
const OperationProblemReanalyze = "/api.core.v1.problem.Problem/Reanalyze"
const OperationProblemRefetch = "/api.core.v1.problem.Problem/Refetch"
const OperationProblemRelatedContests = "/api.core.v1.problem.Problem/RelatedContests"
const OperationProblemRepairQOJTitles = "/api.core.v1.problem.Problem/RepairQOJTitles"
const OperationProblemResetAll = "/api.core.v1.problem.Problem/ResetAll"
const OperationProblemResetQueues = "/api.core.v1.problem.Problem/ResetQueues"
const OperationProblemResume = "/api.core.v1.problem.Problem/Resume"
const OperationProblemRetryFailed = "/api.core.v1.problem.Problem/RetryFailed"
const OperationProblemReviewEdit = "/api.core.v1.problem.Problem/ReviewEdit"
const OperationProblemToggleAnalyze = "/api.core.v1.problem.Problem/ToggleAnalyze"
const OperationProblemToggleFetch = "/api.core.v1.problem.Problem/ToggleFetch"
const OperationProblemUserProfile = "/api.core.v1.problem.Problem/UserProfile"

type ProblemHTTPServer interface {
	// AdminUpdate 站点管理员：直接修改标签/题面（无需审核）
	AdminUpdate(context.Context, *AdminUpdateProblemReq) (*AdminUpdateProblemRes, error)
	Backfill(context.Context, *BackfillReq) (*BackfillRes, error)
	// ClearNowCoderContent 清空牛客题面并强制重爬：只清 content_md，保留 tags / solutions_meta
	ClearNowCoderContent(context.Context, *ClearNowCoderContentReq) (*ClearNowCoderContentRes, error)
	// ClearRecentFailed 清空近期失败：近 6 月 FAILED → FAILED_PERM，停止自动退避重试
	ClearRecentFailed(context.Context, *ClearRecentFailedReq) (*ClearRecentFailedRes, error)
	// EmergencyStop 紧急停止：暂停 AI 并清空分析队列（兼容）
	EmergencyStop(context.Context, *EmergencyStopReq) (*EmergencyStopRes, error)
	// FollowingStatus 关注用户对本题状态（不受组织域限制；需登录）
	FollowingStatus(context.Context, *FollowingStatusReq) (*FollowingStatusRes, error)
	Get(context.Context, *GetProblemReq) (*GetProblemRes, error)
	// Hot 全站热题：近 N 天按提交次数 / 做题人数 / AC 次数综合热度排序
	Hot(context.Context, *HotProblemReq) (*HotProblemRes, error)
	List(context.Context, *ListProblemReq) (*ListProblemRes, error)
	// ListEditRequests 站点管理员：审核申请列表
	ListEditRequests(context.Context, *ListProblemEditReq) (*ListProblemEditRes, error)
	ListSubmissions(context.Context, *ListSubmissionsReq) (*ListSubmissionsRes, error)
	// ListTags 标签聚合（名称 + 题量），供筛选器选择
	ListTags(context.Context, *ListTagsReq) (*ListTagsRes, error)
	// MyPendingEdit 当前用户对该题的待审申请（详情页提示）
	MyPendingEdit(context.Context, *MyPendingEditReq) (*MyPendingEditRes, error)
	Progress(context.Context, *ProgressReq) (*ProgressRes, error)
	// ProposeEdit 登录用户：提交标签/题面修改申请（站点管理员审核）
	ProposeEdit(context.Context, *ProposeProblemEditReq) (*ProposeProblemEditRes, error)
	Reanalyze(context.Context, *ReanalyzeProblemReq) (*ProblemActionRes, error)
	Refetch(context.Context, *RefetchProblemReq) (*ProblemActionRes, error)
	// RelatedContests 本题出现过的比赛（contest_problems 反查，全平台）
	RelatedContests(context.Context, *RelatedContestsReq) (*RelatedContestsRes, error)
	// RepairQOJTitles 全量修复 QOJ 题目标题被识别为「QOJ.ac」的脏数据（后台任务）
	RepairQOJTitles(context.Context, *RepairQOJTitlesReq) (*RepairQOJTitlesRes, error)
	// ResetAll 全部重置：清空 AI 标签，保留题面，可选重新入队分析
	ResetAll(context.Context, *ResetAllReq) (*ResetAllRes, error)
	// ResetQueues 重置 MQ 队列：purge 爬取/分析队列，再按 DB 待爬取/待分析重灌（低优先级）
	ResetQueues(context.Context, *ResetQueuesReq) (*ResetQueuesRes, error)
	// Resume 恢复 AI（兼容）
	Resume(context.Context, *ResumeReq) (*ResumeRes, error)
	// RetryFailed 重试错误队列：默认仅 FAILED；include_permanent=true 时含可恢复的 FAILED_PERM
	RetryFailed(context.Context, *RetryFailedReq) (*RetryFailedRes, error)
	// ReviewEdit 站点管理员：通过/驳回申请
	ReviewEdit(context.Context, *ReviewProblemEditReq) (*ReviewProblemEditRes, error)
	// ToggleAnalyze 暂停/恢复 AI 分析（仅停消费，不清空队列）
	ToggleAnalyze(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error)
	// ToggleFetch 暂停/恢复题面爬取（仅停消费，不清空队列）
	ToggleFetch(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error)
	UserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error)
}

func RegisterProblemHTTPServer(s *http.Server, srv ProblemHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/core/problem/list", _Problem_List0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/tags", _Problem_ListTags0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/hot", _Problem_Hot0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/get", _Problem_Get1_HTTP_Handler(srv))
	r.POST("/v1/core/problem/refetch", _Problem_Refetch0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/reanalyze", _Problem_Reanalyze0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/related-contests", _Problem_RelatedContests0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/submissions", _Problem_ListSubmissions0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/following-status", _Problem_FollowingStatus0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/user-profile", _Problem_UserProfile0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/progress", _Problem_Progress0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/backfill", _Problem_Backfill0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/emergency-stop", _Problem_EmergencyStop0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/reset-all", _Problem_ResetAll0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/resume", _Problem_Resume0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/retry-failed", _Problem_RetryFailed0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/clear-recent-failed", _Problem_ClearRecentFailed0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/clear-nowcoder-content", _Problem_ClearNowCoderContent0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/toggle-analyze", _Problem_ToggleAnalyze0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/toggle-fetch", _Problem_ToggleFetch0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/reset-queues", _Problem_ResetQueues0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/admin-update", _Problem_AdminUpdate0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/propose-edit", _Problem_ProposeEdit0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/edit-requests", _Problem_ListEditRequests0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/review-edit", _Problem_ReviewEdit0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/my-pending-edit", _Problem_MyPendingEdit0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/repair-qoj-titles", _Problem_RepairQOJTitles0_HTTP_Handler(srv))
}

func _Problem_List0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ListTags0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTagsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemListTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTags(ctx, req.(*ListTagsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTagsRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Hot0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HotProblemReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemHot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Hot(ctx, req.(*HotProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HotProblemRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Get1_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProblemRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Refetch0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefetchProblemReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemRefetch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Refetch(ctx, req.(*RefetchProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemActionRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Reanalyze0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReanalyzeProblemReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemReanalyze)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Reanalyze(ctx, req.(*ReanalyzeProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemActionRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_RelatedContests0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RelatedContestsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemRelatedContests)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RelatedContests(ctx, req.(*RelatedContestsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RelatedContestsRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ListSubmissions0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubmissionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemListSubmissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubmissions(ctx, req.(*ListSubmissionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubmissionsRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_FollowingStatus0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FollowingStatusReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemFollowingStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FollowingStatus(ctx, req.(*FollowingStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FollowingStatusRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_UserProfile0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserProfileReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemUserProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserProfile(ctx, req.(*UserProfileReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserProfileRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Progress0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProgressReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Progress(ctx, req.(*ProgressReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProgressRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Backfill0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BackfillReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemBackfill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Backfill(ctx, req.(*BackfillReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BackfillRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_EmergencyStop0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmergencyStopReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemEmergencyStop)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EmergencyStop(ctx, req.(*EmergencyStopReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmergencyStopRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ResetAll0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResetAllReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemResetAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetAll(ctx, req.(*ResetAllReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResetAllRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Resume0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResumeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemResume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Resume(ctx, req.(*ResumeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResumeRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_RetryFailed0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetryFailedReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemRetryFailed)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetryFailed(ctx, req.(*RetryFailedReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RetryFailedRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ClearRecentFailed0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClearRecentFailedReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemClearRecentFailed)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearRecentFailed(ctx, req.(*ClearRecentFailedReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClearRecentFailedRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ClearNowCoderContent0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClearNowCoderContentReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemClearNowCoderContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearNowCoderContent(ctx, req.(*ClearNowCoderContentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClearNowCoderContentRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ToggleAnalyze0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TogglePipelineReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemToggleAnalyze)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleAnalyze(ctx, req.(*TogglePipelineReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TogglePipelineRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ToggleFetch0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TogglePipelineReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemToggleFetch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleFetch(ctx, req.(*TogglePipelineReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TogglePipelineRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ResetQueues0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResetQueuesReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemResetQueues)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetQueues(ctx, req.(*ResetQueuesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResetQueuesRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_AdminUpdate0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminUpdateProblemReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemAdminUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminUpdate(ctx, req.(*AdminUpdateProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUpdateProblemRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ProposeEdit0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProposeProblemEditReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemProposeEdit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProposeEdit(ctx, req.(*ProposeProblemEditReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProposeProblemEditRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ListEditRequests0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemEditReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemListEditRequests)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEditRequests(ctx, req.(*ListProblemEditReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemEditRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ReviewEdit0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReviewProblemEditReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemReviewEdit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReviewEdit(ctx, req.(*ReviewProblemEditReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReviewProblemEditRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_MyPendingEdit0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MyPendingEditReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemMyPendingEdit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MyPendingEdit(ctx, req.(*MyPendingEditReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MyPendingEditRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_RepairQOJTitles0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RepairQOJTitlesReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemRepairQOJTitles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RepairQOJTitles(ctx, req.(*RepairQOJTitlesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RepairQOJTitlesRes)
		return ctx.Result(200, reply)
	}
}

type ProblemHTTPClient interface {
	// AdminUpdate 站点管理员：直接修改标签/题面（无需审核）
	AdminUpdate(ctx context.Context, req *AdminUpdateProblemReq, opts ...http.CallOption) (rsp *AdminUpdateProblemRes, err error)
	Backfill(ctx context.Context, req *BackfillReq, opts ...http.CallOption) (rsp *BackfillRes, err error)
	// ClearNowCoderContent 清空牛客题面并强制重爬：只清 content_md，保留 tags / solutions_meta
	ClearNowCoderContent(ctx context.Context, req *ClearNowCoderContentReq, opts ...http.CallOption) (rsp *ClearNowCoderContentRes, err error)
	// ClearRecentFailed 清空近期失败：近 6 月 FAILED → FAILED_PERM，停止自动退避重试
	ClearRecentFailed(ctx context.Context, req *ClearRecentFailedReq, opts ...http.CallOption) (rsp *ClearRecentFailedRes, err error)
	// EmergencyStop 紧急停止：暂停 AI 并清空分析队列（兼容）
	EmergencyStop(ctx context.Context, req *EmergencyStopReq, opts ...http.CallOption) (rsp *EmergencyStopRes, err error)
	// FollowingStatus 关注用户对本题状态（不受组织域限制；需登录）
	FollowingStatus(ctx context.Context, req *FollowingStatusReq, opts ...http.CallOption) (rsp *FollowingStatusRes, err error)
	Get(ctx context.Context, req *GetProblemReq, opts ...http.CallOption) (rsp *GetProblemRes, err error)
	// Hot 全站热题：近 N 天按提交次数 / 做题人数 / AC 次数综合热度排序
	Hot(ctx context.Context, req *HotProblemReq, opts ...http.CallOption) (rsp *HotProblemRes, err error)
	List(ctx context.Context, req *ListProblemReq, opts ...http.CallOption) (rsp *ListProblemRes, err error)
	// ListEditRequests 站点管理员：审核申请列表
	ListEditRequests(ctx context.Context, req *ListProblemEditReq, opts ...http.CallOption) (rsp *ListProblemEditRes, err error)
	ListSubmissions(ctx context.Context, req *ListSubmissionsReq, opts ...http.CallOption) (rsp *ListSubmissionsRes, err error)
	// ListTags 标签聚合（名称 + 题量），供筛选器选择
	ListTags(ctx context.Context, req *ListTagsReq, opts ...http.CallOption) (rsp *ListTagsRes, err error)
	// MyPendingEdit 当前用户对该题的待审申请（详情页提示）
	MyPendingEdit(ctx context.Context, req *MyPendingEditReq, opts ...http.CallOption) (rsp *MyPendingEditRes, err error)
	Progress(ctx context.Context, req *ProgressReq, opts ...http.CallOption) (rsp *ProgressRes, err error)
	// ProposeEdit 登录用户：提交标签/题面修改申请（站点管理员审核）
	ProposeEdit(ctx context.Context, req *ProposeProblemEditReq, opts ...http.CallOption) (rsp *ProposeProblemEditRes, err error)
	Reanalyze(ctx context.Context, req *ReanalyzeProblemReq, opts ...http.CallOption) (rsp *ProblemActionRes, err error)
	Refetch(ctx context.Context, req *RefetchProblemReq, opts ...http.CallOption) (rsp *ProblemActionRes, err error)
	// RelatedContests 本题出现过的比赛（contest_problems 反查，全平台）
	RelatedContests(ctx context.Context, req *RelatedContestsReq, opts ...http.CallOption) (rsp *RelatedContestsRes, err error)
	// RepairQOJTitles 全量修复 QOJ 题目标题被识别为「QOJ.ac」的脏数据（后台任务）
	RepairQOJTitles(ctx context.Context, req *RepairQOJTitlesReq, opts ...http.CallOption) (rsp *RepairQOJTitlesRes, err error)
	// ResetAll 全部重置：清空 AI 标签，保留题面，可选重新入队分析
	ResetAll(ctx context.Context, req *ResetAllReq, opts ...http.CallOption) (rsp *ResetAllRes, err error)
	// ResetQueues 重置 MQ 队列：purge 爬取/分析队列，再按 DB 待爬取/待分析重灌（低优先级）
	ResetQueues(ctx context.Context, req *ResetQueuesReq, opts ...http.CallOption) (rsp *ResetQueuesRes, err error)
	// Resume 恢复 AI（兼容）
	Resume(ctx context.Context, req *ResumeReq, opts ...http.CallOption) (rsp *ResumeRes, err error)
	// RetryFailed 重试错误队列：默认仅 FAILED；include_permanent=true 时含可恢复的 FAILED_PERM
	RetryFailed(ctx context.Context, req *RetryFailedReq, opts ...http.CallOption) (rsp *RetryFailedRes, err error)
	// ReviewEdit 站点管理员：通过/驳回申请
	ReviewEdit(ctx context.Context, req *ReviewProblemEditReq, opts ...http.CallOption) (rsp *ReviewProblemEditRes, err error)
	// ToggleAnalyze 暂停/恢复 AI 分析（仅停消费，不清空队列）
	ToggleAnalyze(ctx context.Context, req *TogglePipelineReq, opts ...http.CallOption) (rsp *TogglePipelineRes, err error)
	// ToggleFetch 暂停/恢复题面爬取（仅停消费，不清空队列）
	ToggleFetch(ctx context.Context, req *TogglePipelineReq, opts ...http.CallOption) (rsp *TogglePipelineRes, err error)
	UserProfile(ctx context.Context, req *UserProfileReq, opts ...http.CallOption) (rsp *UserProfileRes, err error)
}

type ProblemHTTPClientImpl struct {
	cc *http.Client
}

func NewProblemHTTPClient(client *http.Client) ProblemHTTPClient {
	return &ProblemHTTPClientImpl{client}
}

// AdminUpdate 站点管理员：直接修改标签/题面（无需审核）
func (c *ProblemHTTPClientImpl) AdminUpdate(ctx context.Context, in *AdminUpdateProblemReq, opts ...http.CallOption) (*AdminUpdateProblemRes, error) {
	var out AdminUpdateProblemRes
	pattern := "/v1/core/problem/admin-update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemAdminUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Backfill(ctx context.Context, in *BackfillReq, opts ...http.CallOption) (*BackfillRes, error) {
	var out BackfillRes
	pattern := "/v1/core/problem/backfill"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemBackfill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClearNowCoderContent 清空牛客题面并强制重爬：只清 content_md，保留 tags / solutions_meta
func (c *ProblemHTTPClientImpl) ClearNowCoderContent(ctx context.Context, in *ClearNowCoderContentReq, opts ...http.CallOption) (*ClearNowCoderContentRes, error) {
	var out ClearNowCoderContentRes
	pattern := "/v1/core/problem/clear-nowcoder-content"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemClearNowCoderContent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClearRecentFailed 清空近期失败：近 6 月 FAILED → FAILED_PERM，停止自动退避重试
func (c *ProblemHTTPClientImpl) ClearRecentFailed(ctx context.Context, in *ClearRecentFailedReq, opts ...http.CallOption) (*ClearRecentFailedRes, error) {
	var out ClearRecentFailedRes
	pattern := "/v1/core/problem/clear-recent-failed"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemClearRecentFailed))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EmergencyStop 紧急停止：暂停 AI 并清空分析队列（兼容）
func (c *ProblemHTTPClientImpl) EmergencyStop(ctx context.Context, in *EmergencyStopReq, opts ...http.CallOption) (*EmergencyStopRes, error) {
	var out EmergencyStopRes
	pattern := "/v1/core/problem/emergency-stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemEmergencyStop))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FollowingStatus 关注用户对本题状态（不受组织域限制；需登录）
func (c *ProblemHTTPClientImpl) FollowingStatus(ctx context.Context, in *FollowingStatusReq, opts ...http.CallOption) (*FollowingStatusRes, error) {
	var out FollowingStatusRes
	pattern := "/v1/core/problem/following-status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemFollowingStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Get(ctx context.Context, in *GetProblemReq, opts ...http.CallOption) (*GetProblemRes, error) {
	var out GetProblemRes
	pattern := "/v1/core/problem/get"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Hot 全站热题：近 N 天按提交次数 / 做题人数 / AC 次数综合热度排序
func (c *ProblemHTTPClientImpl) Hot(ctx context.Context, in *HotProblemReq, opts ...http.CallOption) (*HotProblemRes, error) {
	var out HotProblemRes
	pattern := "/v1/core/problem/hot"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemHot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) List(ctx context.Context, in *ListProblemReq, opts ...http.CallOption) (*ListProblemRes, error) {
	var out ListProblemRes
	pattern := "/v1/core/problem/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEditRequests 站点管理员：审核申请列表
func (c *ProblemHTTPClientImpl) ListEditRequests(ctx context.Context, in *ListProblemEditReq, opts ...http.CallOption) (*ListProblemEditRes, error) {
	var out ListProblemEditRes
	pattern := "/v1/core/problem/edit-requests"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemListEditRequests))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) ListSubmissions(ctx context.Context, in *ListSubmissionsReq, opts ...http.CallOption) (*ListSubmissionsRes, error) {
	var out ListSubmissionsRes
	pattern := "/v1/core/problem/submissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemListSubmissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTags 标签聚合（名称 + 题量），供筛选器选择
func (c *ProblemHTTPClientImpl) ListTags(ctx context.Context, in *ListTagsReq, opts ...http.CallOption) (*ListTagsRes, error) {
	var out ListTagsRes
	pattern := "/v1/core/problem/tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemListTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MyPendingEdit 当前用户对该题的待审申请（详情页提示）
func (c *ProblemHTTPClientImpl) MyPendingEdit(ctx context.Context, in *MyPendingEditReq, opts ...http.CallOption) (*MyPendingEditRes, error) {
	var out MyPendingEditRes
	pattern := "/v1/core/problem/my-pending-edit"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemMyPendingEdit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Progress(ctx context.Context, in *ProgressReq, opts ...http.CallOption) (*ProgressRes, error) {
	var out ProgressRes
	pattern := "/v1/core/problem/progress"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ProposeEdit 登录用户：提交标签/题面修改申请（站点管理员审核）
func (c *ProblemHTTPClientImpl) ProposeEdit(ctx context.Context, in *ProposeProblemEditReq, opts ...http.CallOption) (*ProposeProblemEditRes, error) {
	var out ProposeProblemEditRes
	pattern := "/v1/core/problem/propose-edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemProposeEdit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Reanalyze(ctx context.Context, in *ReanalyzeProblemReq, opts ...http.CallOption) (*ProblemActionRes, error) {
	var out ProblemActionRes
	pattern := "/v1/core/problem/reanalyze"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemReanalyze))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Refetch(ctx context.Context, in *RefetchProblemReq, opts ...http.CallOption) (*ProblemActionRes, error) {
	var out ProblemActionRes
	pattern := "/v1/core/problem/refetch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemRefetch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RelatedContests 本题出现过的比赛（contest_problems 反查，全平台）
func (c *ProblemHTTPClientImpl) RelatedContests(ctx context.Context, in *RelatedContestsReq, opts ...http.CallOption) (*RelatedContestsRes, error) {
	var out RelatedContestsRes
	pattern := "/v1/core/problem/related-contests"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemRelatedContests))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RepairQOJTitles 全量修复 QOJ 题目标题被识别为「QOJ.ac」的脏数据（后台任务）
func (c *ProblemHTTPClientImpl) RepairQOJTitles(ctx context.Context, in *RepairQOJTitlesReq, opts ...http.CallOption) (*RepairQOJTitlesRes, error) {
	var out RepairQOJTitlesRes
	pattern := "/v1/core/problem/repair-qoj-titles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemRepairQOJTitles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetAll 全部重置：清空 AI 标签，保留题面，可选重新入队分析
func (c *ProblemHTTPClientImpl) ResetAll(ctx context.Context, in *ResetAllReq, opts ...http.CallOption) (*ResetAllRes, error) {
	var out ResetAllRes
	pattern := "/v1/core/problem/reset-all"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemResetAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetQueues 重置 MQ 队列：purge 爬取/分析队列，再按 DB 待爬取/待分析重灌（低优先级）
func (c *ProblemHTTPClientImpl) ResetQueues(ctx context.Context, in *ResetQueuesReq, opts ...http.CallOption) (*ResetQueuesRes, error) {
	var out ResetQueuesRes
	pattern := "/v1/core/problem/reset-queues"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemResetQueues))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Resume 恢复 AI（兼容）
func (c *ProblemHTTPClientImpl) Resume(ctx context.Context, in *ResumeReq, opts ...http.CallOption) (*ResumeRes, error) {
	var out ResumeRes
	pattern := "/v1/core/problem/resume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemResume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RetryFailed 重试错误队列：默认仅 FAILED；include_permanent=true 时含可恢复的 FAILED_PERM
func (c *ProblemHTTPClientImpl) RetryFailed(ctx context.Context, in *RetryFailedReq, opts ...http.CallOption) (*RetryFailedRes, error) {
	var out RetryFailedRes
	pattern := "/v1/core/problem/retry-failed"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemRetryFailed))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReviewEdit 站点管理员：通过/驳回申请
func (c *ProblemHTTPClientImpl) ReviewEdit(ctx context.Context, in *ReviewProblemEditReq, opts ...http.CallOption) (*ReviewProblemEditRes, error) {
	var out ReviewProblemEditRes
	pattern := "/v1/core/problem/review-edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemReviewEdit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleAnalyze 暂停/恢复 AI 分析（仅停消费，不清空队列）
func (c *ProblemHTTPClientImpl) ToggleAnalyze(ctx context.Context, in *TogglePipelineReq, opts ...http.CallOption) (*TogglePipelineRes, error) {
	var out TogglePipelineRes
	pattern := "/v1/core/problem/toggle-analyze"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemToggleAnalyze))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleFetch 暂停/恢复题面爬取（仅停消费，不清空队列）
func (c *ProblemHTTPClientImpl) ToggleFetch(ctx context.Context, in *TogglePipelineReq, opts ...http.CallOption) (*TogglePipelineRes, error) {
	var out TogglePipelineRes
	pattern := "/v1/core/problem/toggle-fetch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemToggleFetch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) UserProfile(ctx context.Context, in *UserProfileReq, opts ...http.CallOption) (*UserProfileRes, error) {
	var out UserProfileRes
	pattern := "/v1/core/problem/user-profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemUserProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
