// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: user/v1/plugin/luogu.proto

package plugin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeCodeReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LuoguUid            string                 `protobuf:"bytes,1,opt,name=luogu_uid,json=luoguUid,proto3" json:"luogu_uid,omitempty"`
	ClientKind          string                 `protobuf:"bytes,2,opt,name=client_kind,json=clientKind,proto3" json:"client_kind,omitempty"`
	ClientVersion       string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	CodeChallenge       string                 `protobuf:"bytes,4,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	CodeChallengeMethod string                 `protobuf:"bytes,5,opt,name=code_challenge_method,json=codeChallengeMethod,proto3" json:"code_challenge_method,omitempty"`
	State               string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	RiskAccepted        bool                   `protobuf:"varint,7,opt,name=risk_accepted,json=riskAccepted,proto3" json:"risk_accepted,omitempty"`
	RiskVersion         string                 `protobuf:"bytes,8,opt,name=risk_version,json=riskVersion,proto3" json:"risk_version,omitempty"`
	Scope               string                 `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizeCodeReq) Reset() {
	*x = AuthorizeCodeReq{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeCodeReq) ProtoMessage() {}

func (x *AuthorizeCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeCodeReq.ProtoReflect.Descriptor instead.
func (*AuthorizeCodeReq) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeCodeReq) GetLuoguUid() string {
	if x != nil {
		return x.LuoguUid
	}
	return ""
}

func (x *AuthorizeCodeReq) GetClientKind() string {
	if x != nil {
		return x.ClientKind
	}
	return ""
}

func (x *AuthorizeCodeReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AuthorizeCodeReq) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *AuthorizeCodeReq) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *AuthorizeCodeReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizeCodeReq) GetRiskAccepted() bool {
	if x != nil {
		return x.RiskAccepted
	}
	return false
}

func (x *AuthorizeCodeReq) GetRiskVersion() string {
	if x != nil {
		return x.RiskVersion
	}
	return ""
}

func (x *AuthorizeCodeReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type AuthorizeCodeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeCodeRes) Reset() {
	*x = AuthorizeCodeRes{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeCodeRes) ProtoMessage() {}

func (x *AuthorizeCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeCodeRes.ProtoReflect.Descriptor instead.
func (*AuthorizeCodeRes) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeCodeRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthorizeCodeRes) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizeCodeRes) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthorizeCodeRes) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type TokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Verifier      string                 `protobuf:"bytes,2,opt,name=verifier,proto3" json:"verifier,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReq) Reset() {
	*x = TokenReq{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReq) ProtoMessage() {}

func (x *TokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReq.ProtoReflect.Descriptor instead.
func (*TokenReq) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{2}
}

func (x *TokenReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TokenReq) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *TokenReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TokenReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type TokenRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken     string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	AuthorizationId uint64                 `protobuf:"varint,2,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scope           string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenRes) Reset() {
	*x = TokenRes{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRes) ProtoMessage() {}

func (x *TokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRes.ProtoReflect.Descriptor instead.
func (*TokenRes) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRes) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *TokenRes) GetAuthorizationId() uint64 {
	if x != nil {
		return x.AuthorizationId
	}
	return 0
}

func (x *TokenRes) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenRes) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ListAuthorizationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorizationsReq) Reset() {
	*x = ListAuthorizationsReq{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizationsReq) ProtoMessage() {}

func (x *ListAuthorizationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizationsReq.ProtoReflect.Descriptor instead.
func (*ListAuthorizationsReq) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{4}
}

type PluginAuthorizationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ClientKind    string                 `protobuf:"bytes,3,opt,name=client_kind,json=clientKind,proto3" json:"client_kind,omitempty"`
	ClientVersion string                 `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	LuoguUid      string                 `protobuf:"bytes,5,opt,name=luogu_uid,json=luoguUid,proto3" json:"luogu_uid,omitempty"`
	RiskVersion   string                 `protobuf:"bytes,6,opt,name=risk_version,json=riskVersion,proto3" json:"risk_version,omitempty"`
	AcceptedAt    int64                  `protobuf:"varint,7,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastUsedAt    int64                  `protobuf:"varint,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	RevokedAt     int64                  `protobuf:"varint,10,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Scope         string                 `protobuf:"bytes,12,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginAuthorizationInfo) Reset() {
	*x = PluginAuthorizationInfo{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAuthorizationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAuthorizationInfo) ProtoMessage() {}

func (x *PluginAuthorizationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAuthorizationInfo.ProtoReflect.Descriptor instead.
func (*PluginAuthorizationInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{5}
}

func (x *PluginAuthorizationInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PluginAuthorizationInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PluginAuthorizationInfo) GetClientKind() string {
	if x != nil {
		return x.ClientKind
	}
	return ""
}

func (x *PluginAuthorizationInfo) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *PluginAuthorizationInfo) GetLuoguUid() string {
	if x != nil {
		return x.LuoguUid
	}
	return ""
}

func (x *PluginAuthorizationInfo) GetRiskVersion() string {
	if x != nil {
		return x.RiskVersion
	}
	return ""
}

func (x *PluginAuthorizationInfo) GetAcceptedAt() int64 {
	if x != nil {
		return x.AcceptedAt
	}
	return 0
}

func (x *PluginAuthorizationInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *PluginAuthorizationInfo) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

func (x *PluginAuthorizationInfo) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *PluginAuthorizationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PluginAuthorizationInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ListAuthorizationsRes struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Authorizations []*PluginAuthorizationInfo `protobuf:"bytes,1,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAuthorizationsRes) Reset() {
	*x = ListAuthorizationsRes{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizationsRes) ProtoMessage() {}

func (x *ListAuthorizationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizationsRes.ProtoReflect.Descriptor instead.
func (*ListAuthorizationsRes) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuthorizationsRes) GetAuthorizations() []*PluginAuthorizationInfo {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

type RevokeReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationId uint64                 `protobuf:"varint,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	All             bool                   `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeReq) Reset() {
	*x = RevokeReq{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeReq) ProtoMessage() {}

func (x *RevokeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeReq.ProtoReflect.Descriptor instead.
func (*RevokeReq) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeReq) GetAuthorizationId() uint64 {
	if x != nil {
		return x.AuthorizationId
	}
	return 0
}

func (x *RevokeReq) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type RevokeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  uint32                 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRes) Reset() {
	*x = RevokeRes{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRes) ProtoMessage() {}

func (x *RevokeRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRes.ProtoReflect.Descriptor instead.
func (*RevokeRes) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeRes) GetRevokedCount() uint32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

type ValidateLuoguPluginTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLuoguPluginTokenReq) Reset() {
	*x = ValidateLuoguPluginTokenReq{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLuoguPluginTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLuoguPluginTokenReq) ProtoMessage() {}

func (x *ValidateLuoguPluginTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLuoguPluginTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateLuoguPluginTokenReq) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateLuoguPluginTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateLuoguPluginTokenReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ValidateLuoguPluginTokenRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationId uint64                 `protobuf:"varint,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	UserId          uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LuoguUid        string                 `protobuf:"bytes,3,opt,name=luogu_uid,json=luoguUid,proto3" json:"luogu_uid,omitempty"`
	ClientKind      string                 `protobuf:"bytes,4,opt,name=client_kind,json=clientKind,proto3" json:"client_kind,omitempty"`
	ClientVersion   string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	RiskVersion     string                 `protobuf:"bytes,6,opt,name=risk_version,json=riskVersion,proto3" json:"risk_version,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scope           string                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateLuoguPluginTokenRes) Reset() {
	*x = ValidateLuoguPluginTokenRes{}
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLuoguPluginTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLuoguPluginTokenRes) ProtoMessage() {}

func (x *ValidateLuoguPluginTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_plugin_luogu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLuoguPluginTokenRes.ProtoReflect.Descriptor instead.
func (*ValidateLuoguPluginTokenRes) Descriptor() ([]byte, []int) {
	return file_user_v1_plugin_luogu_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateLuoguPluginTokenRes) GetAuthorizationId() uint64 {
	if x != nil {
		return x.AuthorizationId
	}
	return 0
}

func (x *ValidateLuoguPluginTokenRes) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateLuoguPluginTokenRes) GetLuoguUid() string {
	if x != nil {
		return x.LuoguUid
	}
	return ""
}

func (x *ValidateLuoguPluginTokenRes) GetClientKind() string {
	if x != nil {
		return x.ClientKind
	}
	return ""
}

func (x *ValidateLuoguPluginTokenRes) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ValidateLuoguPluginTokenRes) GetRiskVersion() string {
	if x != nil {
		return x.RiskVersion
	}
	return ""
}

func (x *ValidateLuoguPluginTokenRes) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ValidateLuoguPluginTokenRes) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

var File_user_v1_plugin_luogu_proto protoreflect.FileDescriptor

const file_user_v1_plugin_luogu_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/plugin/luogu.proto\x12\x12api.user.v1.plugin\x1a\x1cgoogle/api/annotations.proto\"\xc6\x02\n" +
	"\x10AuthorizeCodeReq\x12\x1b\n" +
	"\tluogu_uid\x18\x01 \x01(\tR\bluoguUid\x12\x1f\n" +
	"\vclient_kind\x18\x02 \x01(\tR\n" +
	"clientKind\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12%\n" +
	"\x0ecode_challenge\x18\x04 \x01(\tR\rcodeChallenge\x122\n" +
	"\x15code_challenge_method\x18\x05 \x01(\tR\x13codeChallengeMethod\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12#\n" +
	"\rrisk_accepted\x18\a \x01(\bR\friskAccepted\x12!\n" +
	"\frisk_version\x18\b \x01(\tR\vriskVersion\x12\x14\n" +
	"\x05scope\x18\t \x01(\tR\x05scope\"q\n" +
	"\x10AuthorizeCodeRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"f\n" +
	"\bTokenReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bverifier\x18\x02 \x01(\tR\bverifier\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\x8d\x01\n" +
	"\bTokenRes\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12)\n" +
	"\x10authorization_id\x18\x02 \x01(\x04R\x0fauthorizationId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\x17\n" +
	"\x15ListAuthorizationsReq\"\x83\x03\n" +
	"\x17PluginAuthorizationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1f\n" +
	"\vclient_kind\x18\x03 \x01(\tR\n" +
	"clientKind\x12%\n" +
	"\x0eclient_version\x18\x04 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tluogu_uid\x18\x05 \x01(\tR\bluoguUid\x12!\n" +
	"\frisk_version\x18\x06 \x01(\tR\vriskVersion\x12\x1f\n" +
	"\vaccepted_at\x18\a \x01(\x03R\n" +
	"acceptedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12 \n" +
	"\flast_used_at\x18\t \x01(\x03R\n" +
	"lastUsedAt\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\n" +
	" \x01(\x03R\trevokedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05scope\x18\f \x01(\tR\x05scope\"l\n" +
	"\x15ListAuthorizationsRes\x12S\n" +
	"\x0eauthorizations\x18\x01 \x03(\v2+.api.user.v1.plugin.PluginAuthorizationInfoR\x0eauthorizations\"H\n" +
	"\tRevokeReq\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\x04R\x0fauthorizationId\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\"0\n" +
	"\tRevokeRes\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\rR\frevokedCount\"I\n" +
	"\x1bValidateLuoguPluginTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"\x9e\x02\n" +
	"\x1bValidateLuoguPluginTokenRes\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\x04R\x0fauthorizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tluogu_uid\x18\x03 \x01(\tR\bluoguUid\x12\x1f\n" +
	"\vclient_kind\x18\x04 \x01(\tR\n" +
	"clientKind\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\x12!\n" +
	"\frisk_version\x18\x06 \x01(\tR\vriskVersion\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05scope\x18\b \x01(\tR\x05scope2\x93\x05\n" +
	"\vLuoguPlugin\x12\x8c\x01\n" +
	"\rAuthorizeCode\x12$.api.user.v1.plugin.AuthorizeCodeReq\x1a$.api.user.v1.plugin.AuthorizeCodeRes\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/user/plugin/luogu/authorize-code\x12k\n" +
	"\x05Token\x12\x1c.api.user.v1.plugin.TokenReq\x1a\x1c.api.user.v1.plugin.TokenRes\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/user/plugin/luogu/token\x12\x98\x01\n" +
	"\x12ListAuthorizations\x12).api.user.v1.plugin.ListAuthorizationsReq\x1a).api.user.v1.plugin.ListAuthorizationsRes\",\x82\xd3\xe4\x93\x02&\x12$/v1/user/plugin/luogu/authorizations\x12o\n" +
	"\x06Revoke\x12\x1d.api.user.v1.plugin.RevokeReq\x1a\x1d.api.user.v1.plugin.RevokeRes\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/user/plugin/luogu/revoke\x12|\n" +
	"\x18ValidateLuoguPluginToken\x12/.api.user.v1.plugin.ValidateLuoguPluginTokenReq\x1a/.api.user.v1.plugin.ValidateLuoguPluginTokenResB;\n" +
	"\x12api.user.v1.pluginP\x01Z#cwxu-algo/api/user/v1/plugin;pluginb\x06proto3"

var (
	file_user_v1_plugin_luogu_proto_rawDescOnce sync.Once
	file_user_v1_plugin_luogu_proto_rawDescData []byte
)

func file_user_v1_plugin_luogu_proto_rawDescGZIP() []byte {
	file_user_v1_plugin_luogu_proto_rawDescOnce.Do(func() {
		file_user_v1_plugin_luogu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_plugin_luogu_proto_rawDesc), len(file_user_v1_plugin_luogu_proto_rawDesc)))
	})
	return file_user_v1_plugin_luogu_proto_rawDescData
}

var file_user_v1_plugin_luogu_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_v1_plugin_luogu_proto_goTypes = []any{
	(*AuthorizeCodeReq)(nil),            // 0: api.user.v1.plugin.AuthorizeCodeReq
	(*AuthorizeCodeRes)(nil),            // 1: api.user.v1.plugin.AuthorizeCodeRes
	(*TokenReq)(nil),                    // 2: api.user.v1.plugin.TokenReq
	(*TokenRes)(nil),                    // 3: api.user.v1.plugin.TokenRes
	(*ListAuthorizationsReq)(nil),       // 4: api.user.v1.plugin.ListAuthorizationsReq
	(*PluginAuthorizationInfo)(nil),     // 5: api.user.v1.plugin.PluginAuthorizationInfo
	(*ListAuthorizationsRes)(nil),       // 6: api.user.v1.plugin.ListAuthorizationsRes
	(*RevokeReq)(nil),                   // 7: api.user.v1.plugin.RevokeReq
	(*RevokeRes)(nil),                   // 8: api.user.v1.plugin.RevokeRes
	(*ValidateLuoguPluginTokenReq)(nil), // 9: api.user.v1.plugin.ValidateLuoguPluginTokenReq
	(*ValidateLuoguPluginTokenRes)(nil), // 10: api.user.v1.plugin.ValidateLuoguPluginTokenRes
}
var file_user_v1_plugin_luogu_proto_depIdxs = []int32{
	5,  // 0: api.user.v1.plugin.ListAuthorizationsRes.authorizations:type_name -> api.user.v1.plugin.PluginAuthorizationInfo
	0,  // 1: api.user.v1.plugin.LuoguPlugin.AuthorizeCode:input_type -> api.user.v1.plugin.AuthorizeCodeReq
	2,  // 2: api.user.v1.plugin.LuoguPlugin.Token:input_type -> api.user.v1.plugin.TokenReq
	4,  // 3: api.user.v1.plugin.LuoguPlugin.ListAuthorizations:input_type -> api.user.v1.plugin.ListAuthorizationsReq
	7,  // 4: api.user.v1.plugin.LuoguPlugin.Revoke:input_type -> api.user.v1.plugin.RevokeReq
	9,  // 5: api.user.v1.plugin.LuoguPlugin.ValidateLuoguPluginToken:input_type -> api.user.v1.plugin.ValidateLuoguPluginTokenReq
	1,  // 6: api.user.v1.plugin.LuoguPlugin.AuthorizeCode:output_type -> api.user.v1.plugin.AuthorizeCodeRes
	3,  // 7: api.user.v1.plugin.LuoguPlugin.Token:output_type -> api.user.v1.plugin.TokenRes
	6,  // 8: api.user.v1.plugin.LuoguPlugin.ListAuthorizations:output_type -> api.user.v1.plugin.ListAuthorizationsRes
	8,  // 9: api.user.v1.plugin.LuoguPlugin.Revoke:output_type -> api.user.v1.plugin.RevokeRes
	10, // 10: api.user.v1.plugin.LuoguPlugin.ValidateLuoguPluginToken:output_type -> api.user.v1.plugin.ValidateLuoguPluginTokenRes
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_plugin_luogu_proto_init() }
func file_user_v1_plugin_luogu_proto_init() {
	if File_user_v1_plugin_luogu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_plugin_luogu_proto_rawDesc), len(file_user_v1_plugin_luogu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_plugin_luogu_proto_goTypes,
		DependencyIndexes: file_user_v1_plugin_luogu_proto_depIdxs,
		MessageInfos:      file_user_v1_plugin_luogu_proto_msgTypes,
	}.Build()
	File_user_v1_plugin_luogu_proto = out.File
	file_user_v1_plugin_luogu_proto_goTypes = nil
	file_user_v1_plugin_luogu_proto_depIdxs = nil
}
