// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user/v1/notification/notification.proto

package notification

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ActorId       int64                  `protobuf:"varint,5,opt,name=actorId,proto3" json:"actorId,omitempty"`
	RefType       string                 `protobuf:"bytes,6,opt,name=refType,proto3" json:"refType,omitempty"`
	RefId         int64                  `protobuf:"varint,7,opt,name=refId,proto3" json:"refId,omitempty"`
	ProblemId     int64                  `protobuf:"varint,8,opt,name=problemId,proto3" json:"problemId,omitempty"`
	Payload       string                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	IsRead        bool                   `protobuf:"varint,10,opt,name=isRead,proto3" json:"isRead,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationItem) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *NotificationItem) GetRefType() string {
	if x != nil {
		return x.RefType
	}
	return ""
}

func (x *NotificationItem) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *NotificationItem) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *NotificationItem) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *NotificationItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*NotificationItem    `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,7,opt,name=unreadCount,proto3" json:"unreadCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRes) Reset() {
	*x = ListRes{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRes) ProtoMessage() {}

func (x *ListRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRes.ProtoReflect.Descriptor instead.
func (*ListRes) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListRes) GetList() []*NotificationItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRes) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRes) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type UnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountReq) Reset() {
	*x = UnreadCountReq{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountReq) ProtoMessage() {}

func (x *UnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountReq.ProtoReflect.Descriptor instead.
func (*UnreadCountReq) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{3}
}

type UnreadCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,3,opt,name=unreadCount,proto3" json:"unreadCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountRes) Reset() {
	*x = UnreadCountRes{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountRes) ProtoMessage() {}

func (x *UnreadCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountRes.ProtoReflect.Descriptor instead.
func (*UnreadCountRes) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UnreadCountRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnreadCountRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnreadCountRes) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReq) Reset() {
	*x = ReadReq{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReq) ProtoMessage() {}

func (x *ReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReq.ProtoReflect.Descriptor instead.
func (*ReadReq) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ReadReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReadRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRes) Reset() {
	*x = ReadRes{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRes) ProtoMessage() {}

func (x *ReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRes.ProtoReflect.Descriptor instead.
func (*ReadRes) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllReq) Reset() {
	*x = ReadAllReq{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllReq) ProtoMessage() {}

func (x *ReadAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllReq.ProtoReflect.Descriptor instead.
func (*ReadAllReq) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{7}
}

type ReadAllRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllRes) Reset() {
	*x = ReadAllRes{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllRes) ProtoMessage() {}

func (x *ReadAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllRes.ProtoReflect.Descriptor instead.
func (*ReadAllRes) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadAllRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClearAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAllReq) Reset() {
	*x = ClearAllReq{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllReq) ProtoMessage() {}

func (x *ClearAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllReq.ProtoReflect.Descriptor instead.
func (*ClearAllReq) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{9}
}

type ClearAllRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Deleted       int64                  `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAllRes) Reset() {
	*x = ClearAllRes{}
	mi := &file_user_v1_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllRes) ProtoMessage() {}

func (x *ClearAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllRes.ProtoReflect.Descriptor instead.
func (*ClearAllRes) Descriptor() ([]byte, []int) {
	return file_user_v1_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *ClearAllRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearAllRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClearAllRes) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_user_v1_notification_notification_proto protoreflect.FileDescriptor

const file_user_v1_notification_notification_proto_rawDesc = "" +
	"\n" +
	"'user/v1/notification/notification.proto\x12\x18api.user.v1.notification\x1a\x1cgoogle/api/annotations.proto\"\x98\x02\n" +
	"\x10NotificationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\aactorId\x18\x05 \x01(\x03R\aactorId\x12\x18\n" +
	"\arefType\x18\x06 \x01(\tR\arefType\x12\x14\n" +
	"\x05refId\x18\a \x01(\x03R\x05refId\x12\x1c\n" +
	"\tproblemId\x18\b \x01(\x03R\tproblemId\x12\x18\n" +
	"\apayload\x18\t \x01(\tR\apayload\x12\x16\n" +
	"\x06isRead\x18\n" +
	" \x01(\bR\x06isRead\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\"9\n" +
	"\aListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"\xe5\x01\n" +
	"\aListRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04list\x18\x03 \x03(\v2*.api.user.v1.notification.NotificationItemR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x06 \x01(\x03R\bpageSize\x12 \n" +
	"\vunreadCount\x18\a \x01(\x03R\vunreadCount\"\x10\n" +
	"\x0eUnreadCountReq\"f\n" +
	"\x0eUnreadCountRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vunreadCount\x18\x03 \x01(\x03R\vunreadCount\"\x1b\n" +
	"\aReadReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"=\n" +
	"\aReadRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\f\n" +
	"\n" +
	"ReadAllReq\"@\n" +
	"\n" +
	"ReadAllRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vClearAllReq\"[\n" +
	"\vClearAllRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\x03R\adeleted2\x8f\x05\n" +
	"\fNotification\x12p\n" +
	"\x04List\x12!.api.user.v1.notification.ListReq\x1a!.api.user.v1.notification.ListRes\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/user/notification/list\x12\x8d\x01\n" +
	"\vUnreadCount\x12(.api.user.v1.notification.UnreadCountReq\x1a(.api.user.v1.notification.UnreadCountRes\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/user/notification/unread-count\x12s\n" +
	"\x04Read\x12!.api.user.v1.notification.ReadReq\x1a!.api.user.v1.notification.ReadRes\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/user/notification/read\x12\x80\x01\n" +
	"\aReadAll\x12$.api.user.v1.notification.ReadAllReq\x1a$.api.user.v1.notification.ReadAllRes\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/user/notification/read-all\x12\x84\x01\n" +
	"\bClearAll\x12%.api.user.v1.notification.ClearAllReq\x1a%.api.user.v1.notification.ClearAllRes\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/user/notification/clear-allBM\n" +
	"\x18api.user.v1.notificationP\x01Z/cwxu-algo/api/user/v1/notification;notificationb\x06proto3"

var (
	file_user_v1_notification_notification_proto_rawDescOnce sync.Once
	file_user_v1_notification_notification_proto_rawDescData []byte
)

func file_user_v1_notification_notification_proto_rawDescGZIP() []byte {
	file_user_v1_notification_notification_proto_rawDescOnce.Do(func() {
		file_user_v1_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_notification_notification_proto_rawDesc), len(file_user_v1_notification_notification_proto_rawDesc)))
	})
	return file_user_v1_notification_notification_proto_rawDescData
}

var file_user_v1_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_v1_notification_notification_proto_goTypes = []any{
	(*NotificationItem)(nil), // 0: api.user.v1.notification.NotificationItem
	(*ListReq)(nil),          // 1: api.user.v1.notification.ListReq
	(*ListRes)(nil),          // 2: api.user.v1.notification.ListRes
	(*UnreadCountReq)(nil),   // 3: api.user.v1.notification.UnreadCountReq
	(*UnreadCountRes)(nil),   // 4: api.user.v1.notification.UnreadCountRes
	(*ReadReq)(nil),          // 5: api.user.v1.notification.ReadReq
	(*ReadRes)(nil),          // 6: api.user.v1.notification.ReadRes
	(*ReadAllReq)(nil),       // 7: api.user.v1.notification.ReadAllReq
	(*ReadAllRes)(nil),       // 8: api.user.v1.notification.ReadAllRes
	(*ClearAllReq)(nil),      // 9: api.user.v1.notification.ClearAllReq
	(*ClearAllRes)(nil),      // 10: api.user.v1.notification.ClearAllRes
}
var file_user_v1_notification_notification_proto_depIdxs = []int32{
	0,  // 0: api.user.v1.notification.ListRes.list:type_name -> api.user.v1.notification.NotificationItem
	1,  // 1: api.user.v1.notification.Notification.List:input_type -> api.user.v1.notification.ListReq
	3,  // 2: api.user.v1.notification.Notification.UnreadCount:input_type -> api.user.v1.notification.UnreadCountReq
	5,  // 3: api.user.v1.notification.Notification.Read:input_type -> api.user.v1.notification.ReadReq
	7,  // 4: api.user.v1.notification.Notification.ReadAll:input_type -> api.user.v1.notification.ReadAllReq
	9,  // 5: api.user.v1.notification.Notification.ClearAll:input_type -> api.user.v1.notification.ClearAllReq
	2,  // 6: api.user.v1.notification.Notification.List:output_type -> api.user.v1.notification.ListRes
	4,  // 7: api.user.v1.notification.Notification.UnreadCount:output_type -> api.user.v1.notification.UnreadCountRes
	6,  // 8: api.user.v1.notification.Notification.Read:output_type -> api.user.v1.notification.ReadRes
	8,  // 9: api.user.v1.notification.Notification.ReadAll:output_type -> api.user.v1.notification.ReadAllRes
	10, // 10: api.user.v1.notification.Notification.ClearAll:output_type -> api.user.v1.notification.ClearAllRes
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_notification_notification_proto_init() }
func file_user_v1_notification_notification_proto_init() {
	if File_user_v1_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_notification_notification_proto_rawDesc), len(file_user_v1_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_notification_notification_proto_goTypes,
		DependencyIndexes: file_user_v1_notification_notification_proto_depIdxs,
		MessageInfos:      file_user_v1_notification_notification_proto_msgTypes,
	}.Build()
	File_user_v1_notification_notification_proto = out.File
	file_user_v1_notification_notification_proto_goTypes = nil
	file_user_v1_notification_notification_proto_depIdxs = nil
}
