// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: user/v1/paste/paste.proto

package paste

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paste_Create_FullMethodName    = "/api.user.v1.paste.Paste/Create"
	Paste_Get_FullMethodName       = "/api.user.v1.paste.Paste/Get"
	Paste_Mine_FullMethodName      = "/api.user.v1.paste.Paste/Mine"
	Paste_Delete_FullMethodName    = "/api.user.v1.paste.Paste/Delete"
	Paste_AdminList_FullMethodName = "/api.user.v1.paste.Paste/AdminList"
)

// PasteClient is the client API for Paste service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Paste 文本/代码粘贴板
// 实现位于 user/internal/service/paste.go（由手写 HTTP 路由迁移而来）。
// 路径前缀：/v1/user/paste/*
type PasteClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error)
	// 公开查看（JWT 白名单）
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error)
	Mine(ctx context.Context, in *MineReq, opts ...grpc.CallOption) (*MineRes, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRes, error)
	// 站管 / 内容治理：查看当前全部未过期粘贴内容（事后审查）
	AdminList(ctx context.Context, in *AdminListReq, opts ...grpc.CallOption) (*AdminListRes, error)
}

type pasteClient struct {
	cc grpc.ClientConnInterface
}

func NewPasteClient(cc grpc.ClientConnInterface) PasteClient {
	return &pasteClient{cc}
}

func (c *pasteClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRes)
	err := c.cc.Invoke(ctx, Paste_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pasteClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRes)
	err := c.cc.Invoke(ctx, Paste_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pasteClient) Mine(ctx context.Context, in *MineReq, opts ...grpc.CallOption) (*MineRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MineRes)
	err := c.cc.Invoke(ctx, Paste_Mine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pasteClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRes)
	err := c.cc.Invoke(ctx, Paste_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pasteClient) AdminList(ctx context.Context, in *AdminListReq, opts ...grpc.CallOption) (*AdminListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListRes)
	err := c.cc.Invoke(ctx, Paste_AdminList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasteServer is the server API for Paste service.
// All implementations must embed UnimplementedPasteServer
// for forward compatibility.
//
// Paste 文本/代码粘贴板
// 实现位于 user/internal/service/paste.go（由手写 HTTP 路由迁移而来）。
// 路径前缀：/v1/user/paste/*
type PasteServer interface {
	Create(context.Context, *CreateReq) (*CreateRes, error)
	// 公开查看（JWT 白名单）
	Get(context.Context, *GetReq) (*GetRes, error)
	Mine(context.Context, *MineReq) (*MineRes, error)
	Delete(context.Context, *DeleteReq) (*DeleteRes, error)
	// 站管 / 内容治理：查看当前全部未过期粘贴内容（事后审查）
	AdminList(context.Context, *AdminListReq) (*AdminListRes, error)
	mustEmbedUnimplementedPasteServer()
}

// UnimplementedPasteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPasteServer struct{}

func (UnimplementedPasteServer) Create(context.Context, *CreateReq) (*CreateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPasteServer) Get(context.Context, *GetReq) (*GetRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPasteServer) Mine(context.Context, *MineReq) (*MineRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Mine not implemented")
}
func (UnimplementedPasteServer) Delete(context.Context, *DeleteReq) (*DeleteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPasteServer) AdminList(context.Context, *AdminListReq) (*AdminListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminList not implemented")
}
func (UnimplementedPasteServer) mustEmbedUnimplementedPasteServer() {}
func (UnimplementedPasteServer) testEmbeddedByValue()               {}

// UnsafePasteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasteServer will
// result in compilation errors.
type UnsafePasteServer interface {
	mustEmbedUnimplementedPasteServer()
}

func RegisterPasteServer(s grpc.ServiceRegistrar, srv PasteServer) {
	// If the following call panics, it indicates UnimplementedPasteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paste_ServiceDesc, srv)
}

func _Paste_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paste_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paste_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paste_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paste_Mine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServer).Mine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paste_Mine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServer).Mine(ctx, req.(*MineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paste_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paste_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paste_AdminList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServer).AdminList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paste_AdminList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServer).AdminList(ctx, req.(*AdminListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Paste_ServiceDesc is the grpc.ServiceDesc for Paste service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paste_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.v1.paste.Paste",
	HandlerType: (*PasteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Paste_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Paste_Get_Handler,
		},
		{
			MethodName: "Mine",
			Handler:    _Paste_Mine_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Paste_Delete_Handler,
		},
		{
			MethodName: "AdminList",
			Handler:    _Paste_AdminList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/paste/paste.proto",
}
