server:
  http:
    addr: 0.0.0.0:8000
    timeout: 90s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 90s
  reg_dsn: consul:8500
  jwt_secret: ""
  jwt_private_key: "${JWT_PRIVATE_KEY}"
  jwt_public_key: "${JWT_PUBLIC_KEY}"
data:
  database:
    driver: postgres
    source: "${USER_DATABASE_DSN}"
  redis:
    addr: "${REDIS_ADDR}"
    password: "${REDIS_PASSWORD}"
    read_timeout: 2s
    write_timeout: 2s
support_center:
  base_url: ""
  product_id: ""
  sign_key: ""
  timeout: 5s
