// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: core/v1/spider/spider.proto

package spider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Spider_SetSpider_FullMethodName              = "/api.core.v1.spider.Spider/SetSpider"
	Spider_GetSpider_FullMethodName              = "/api.core.v1.spider.Spider/GetSpider"
	Spider_Update_FullMethodName                 = "/api.core.v1.spider.Spider/Update"
	Spider_UpdateAll_FullMethodName              = "/api.core.v1.spider.Spider/UpdateAll"
	Spider_PurgeUserData_FullMethodName          = "/api.core.v1.spider.Spider/PurgeUserData"
	Spider_SubmitInventory_FullMethodName        = "/api.core.v1.spider.Spider/SubmitInventory"
	Spider_PurgeSubmitsAndRecrawl_FullMethodName = "/api.core.v1.spider.Spider/PurgeSubmitsAndRecrawl"
	Spider_EnqueueUserSpider_FullMethodName      = "/api.core.v1.spider.Spider/EnqueueUserSpider"
	Spider_GetSpiderMonitor_FullMethodName       = "/api.core.v1.spider.Spider/GetSpiderMonitor"
	Spider_TogglePlatform_FullMethodName         = "/api.core.v1.spider.Spider/TogglePlatform"
	Spider_UpdatePlatform_FullMethodName         = "/api.core.v1.spider.Spider/UpdatePlatform"
	Spider_RepairContestCells_FullMethodName     = "/api.core.v1.spider.Spider/RepairContestCells"
	Spider_GetPlatformUsers_FullMethodName       = "/api.core.v1.spider.Spider/GetPlatformUsers"
)

// SpiderClient is the client API for Spider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiderClient interface {
	SetSpider(ctx context.Context, in *SetSpiderReq, opts ...grpc.CallOption) (*SetSpiderRep, error)
	GetSpider(ctx context.Context, in *GetSpiderReq, opts ...grpc.CallOption) (*GetSpiderRep, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateRes, error)
	// 管理员一键全量更新所有已绑定 OJ 的用户
	UpdateAll(ctx context.Context, in *UpdateAllReq, opts ...grpc.CallOption) (*UpdateAllRes, error)
	// 删除用户时清空该用户在 core 的全部数据（OJ 绑定 / 提交 / 比赛记录）
	PurgeUserData(ctx context.Context, in *PurgeUserDataReq, opts ...grpc.CallOption) (*PurgeUserDataRes, error)
	// 运维：提交库存（明细 / 账本真实行数，仅站管）
	SubmitInventory(ctx context.Context, in *SubmitInventoryReq, opts ...grpc.CallOption) (*SubmitInventoryRes, error)
	// 运维：清空全部提交相关数据并全量重爬（仅站管；confirm=PURGE_SUBMITS）
	PurgeSubmitsAndRecrawl(ctx context.Context, in *PurgeSubmitsAndRecrawlReq, opts ...grpc.CallOption) (*PurgeSubmitsAndRecrawlRes, error)
	// 内部：休眠唤醒 / 服务间入队爬虫（无 HTTP）
	EnqueueUserSpider(ctx context.Context, in *EnqueueUserSpiderReq, opts ...grpc.CallOption) (*EnqueueUserSpiderRes, error)
	// 运维：各 OJ 爬虫模块监控（仅站管）
	GetSpiderMonitor(ctx context.Context, in *SpiderMonitorReq, opts ...grpc.CallOption) (*SpiderMonitorRes, error)
	// 站管：暂停 / 恢复某 OJ 的爬虫同步（body: { platform, enabled }）
	TogglePlatform(ctx context.Context, in *TogglePlatformReq, opts ...grpc.CallOption) (*TogglePlatformRes, error)
	// 站管：按平台全量回填（body: { platform }；如力扣比赛记录）。
	// 仅入队该平台已绑定用户的 needAll 任务，并强制清去重。
	UpdatePlatform(ctx context.Context, in *UpdatePlatformReq, opts ...grpc.CallOption) (*UpdatePlatformRes, error)
	// 站管：幂等修复 AtCoder 赛时提交明细相关脏数据（external_id / 赛后练习格 / relative_sec）
	RepairContestCells(ctx context.Context, in *RepairContestCellsReq, opts ...grpc.CallOption) (*RepairContestCellsRes, error)
	// 站管：某 OJ 的绑定用户列表（仅站管）
	GetPlatformUsers(ctx context.Context, in *GetPlatformUsersReq, opts ...grpc.CallOption) (*GetPlatformUsersRes, error)
}

type spiderClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderClient(cc grpc.ClientConnInterface) SpiderClient {
	return &spiderClient{cc}
}

func (c *spiderClient) SetSpider(ctx context.Context, in *SetSpiderReq, opts ...grpc.CallOption) (*SetSpiderRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSpiderRep)
	err := c.cc.Invoke(ctx, Spider_SetSpider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) GetSpider(ctx context.Context, in *GetSpiderReq, opts ...grpc.CallOption) (*GetSpiderRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpiderRep)
	err := c.cc.Invoke(ctx, Spider_GetSpider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRes)
	err := c.cc.Invoke(ctx, Spider_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) UpdateAll(ctx context.Context, in *UpdateAllReq, opts ...grpc.CallOption) (*UpdateAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAllRes)
	err := c.cc.Invoke(ctx, Spider_UpdateAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) PurgeUserData(ctx context.Context, in *PurgeUserDataReq, opts ...grpc.CallOption) (*PurgeUserDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeUserDataRes)
	err := c.cc.Invoke(ctx, Spider_PurgeUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) SubmitInventory(ctx context.Context, in *SubmitInventoryReq, opts ...grpc.CallOption) (*SubmitInventoryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInventoryRes)
	err := c.cc.Invoke(ctx, Spider_SubmitInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) PurgeSubmitsAndRecrawl(ctx context.Context, in *PurgeSubmitsAndRecrawlReq, opts ...grpc.CallOption) (*PurgeSubmitsAndRecrawlRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeSubmitsAndRecrawlRes)
	err := c.cc.Invoke(ctx, Spider_PurgeSubmitsAndRecrawl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) EnqueueUserSpider(ctx context.Context, in *EnqueueUserSpiderReq, opts ...grpc.CallOption) (*EnqueueUserSpiderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueUserSpiderRes)
	err := c.cc.Invoke(ctx, Spider_EnqueueUserSpider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) GetSpiderMonitor(ctx context.Context, in *SpiderMonitorReq, opts ...grpc.CallOption) (*SpiderMonitorRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpiderMonitorRes)
	err := c.cc.Invoke(ctx, Spider_GetSpiderMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) TogglePlatform(ctx context.Context, in *TogglePlatformReq, opts ...grpc.CallOption) (*TogglePlatformRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TogglePlatformRes)
	err := c.cc.Invoke(ctx, Spider_TogglePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) UpdatePlatform(ctx context.Context, in *UpdatePlatformReq, opts ...grpc.CallOption) (*UpdatePlatformRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlatformRes)
	err := c.cc.Invoke(ctx, Spider_UpdatePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) RepairContestCells(ctx context.Context, in *RepairContestCellsReq, opts ...grpc.CallOption) (*RepairContestCellsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepairContestCellsRes)
	err := c.cc.Invoke(ctx, Spider_RepairContestCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) GetPlatformUsers(ctx context.Context, in *GetPlatformUsersReq, opts ...grpc.CallOption) (*GetPlatformUsersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformUsersRes)
	err := c.cc.Invoke(ctx, Spider_GetPlatformUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServer is the server API for Spider service.
// All implementations must embed UnimplementedSpiderServer
// for forward compatibility.
type SpiderServer interface {
	SetSpider(context.Context, *SetSpiderReq) (*SetSpiderRep, error)
	GetSpider(context.Context, *GetSpiderReq) (*GetSpiderRep, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
	// 管理员一键全量更新所有已绑定 OJ 的用户
	UpdateAll(context.Context, *UpdateAllReq) (*UpdateAllRes, error)
	// 删除用户时清空该用户在 core 的全部数据（OJ 绑定 / 提交 / 比赛记录）
	PurgeUserData(context.Context, *PurgeUserDataReq) (*PurgeUserDataRes, error)
	// 运维：提交库存（明细 / 账本真实行数，仅站管）
	SubmitInventory(context.Context, *SubmitInventoryReq) (*SubmitInventoryRes, error)
	// 运维：清空全部提交相关数据并全量重爬（仅站管；confirm=PURGE_SUBMITS）
	PurgeSubmitsAndRecrawl(context.Context, *PurgeSubmitsAndRecrawlReq) (*PurgeSubmitsAndRecrawlRes, error)
	// 内部：休眠唤醒 / 服务间入队爬虫（无 HTTP）
	EnqueueUserSpider(context.Context, *EnqueueUserSpiderReq) (*EnqueueUserSpiderRes, error)
	// 运维：各 OJ 爬虫模块监控（仅站管）
	GetSpiderMonitor(context.Context, *SpiderMonitorReq) (*SpiderMonitorRes, error)
	// 站管：暂停 / 恢复某 OJ 的爬虫同步（body: { platform, enabled }）
	TogglePlatform(context.Context, *TogglePlatformReq) (*TogglePlatformRes, error)
	// 站管：按平台全量回填（body: { platform }；如力扣比赛记录）。
	// 仅入队该平台已绑定用户的 needAll 任务，并强制清去重。
	UpdatePlatform(context.Context, *UpdatePlatformReq) (*UpdatePlatformRes, error)
	// 站管：幂等修复 AtCoder 赛时提交明细相关脏数据（external_id / 赛后练习格 / relative_sec）
	RepairContestCells(context.Context, *RepairContestCellsReq) (*RepairContestCellsRes, error)
	// 站管：某 OJ 的绑定用户列表（仅站管）
	GetPlatformUsers(context.Context, *GetPlatformUsersReq) (*GetPlatformUsersRes, error)
	mustEmbedUnimplementedSpiderServer()
}

// UnimplementedSpiderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpiderServer struct{}

func (UnimplementedSpiderServer) SetSpider(context.Context, *SetSpiderReq) (*SetSpiderRep, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSpider not implemented")
}
func (UnimplementedSpiderServer) GetSpider(context.Context, *GetSpiderReq) (*GetSpiderRep, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpider not implemented")
}
func (UnimplementedSpiderServer) Update(context.Context, *UpdateReq) (*UpdateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSpiderServer) UpdateAll(context.Context, *UpdateAllReq) (*UpdateAllRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAll not implemented")
}
func (UnimplementedSpiderServer) PurgeUserData(context.Context, *PurgeUserDataReq) (*PurgeUserDataRes, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeUserData not implemented")
}
func (UnimplementedSpiderServer) SubmitInventory(context.Context, *SubmitInventoryReq) (*SubmitInventoryRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInventory not implemented")
}
func (UnimplementedSpiderServer) PurgeSubmitsAndRecrawl(context.Context, *PurgeSubmitsAndRecrawlReq) (*PurgeSubmitsAndRecrawlRes, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeSubmitsAndRecrawl not implemented")
}
func (UnimplementedSpiderServer) EnqueueUserSpider(context.Context, *EnqueueUserSpiderReq) (*EnqueueUserSpiderRes, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueUserSpider not implemented")
}
func (UnimplementedSpiderServer) GetSpiderMonitor(context.Context, *SpiderMonitorReq) (*SpiderMonitorRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpiderMonitor not implemented")
}
func (UnimplementedSpiderServer) TogglePlatform(context.Context, *TogglePlatformReq) (*TogglePlatformRes, error) {
	return nil, status.Error(codes.Unimplemented, "method TogglePlatform not implemented")
}
func (UnimplementedSpiderServer) UpdatePlatform(context.Context, *UpdatePlatformReq) (*UpdatePlatformRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlatform not implemented")
}
func (UnimplementedSpiderServer) RepairContestCells(context.Context, *RepairContestCellsReq) (*RepairContestCellsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RepairContestCells not implemented")
}
func (UnimplementedSpiderServer) GetPlatformUsers(context.Context, *GetPlatformUsersReq) (*GetPlatformUsersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformUsers not implemented")
}
func (UnimplementedSpiderServer) mustEmbedUnimplementedSpiderServer() {}
func (UnimplementedSpiderServer) testEmbeddedByValue()                {}

// UnsafeSpiderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiderServer will
// result in compilation errors.
type UnsafeSpiderServer interface {
	mustEmbedUnimplementedSpiderServer()
}

func RegisterSpiderServer(s grpc.ServiceRegistrar, srv SpiderServer) {
	// If the following call panics, it indicates UnimplementedSpiderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Spider_ServiceDesc, srv)
}

func _Spider_SetSpider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).SetSpider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_SetSpider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).SetSpider(ctx, req.(*SetSpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_GetSpider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetSpider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetSpider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetSpider(ctx, req.(*GetSpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_UpdateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).UpdateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_UpdateAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).UpdateAll(ctx, req.(*UpdateAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_PurgeUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeUserDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).PurgeUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_PurgeUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).PurgeUserData(ctx, req.(*PurgeUserDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_SubmitInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).SubmitInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_SubmitInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).SubmitInventory(ctx, req.(*SubmitInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_PurgeSubmitsAndRecrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeSubmitsAndRecrawlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).PurgeSubmitsAndRecrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_PurgeSubmitsAndRecrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).PurgeSubmitsAndRecrawl(ctx, req.(*PurgeSubmitsAndRecrawlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_EnqueueUserSpider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueUserSpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).EnqueueUserSpider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_EnqueueUserSpider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).EnqueueUserSpider(ctx, req.(*EnqueueUserSpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_GetSpiderMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiderMonitorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetSpiderMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetSpiderMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetSpiderMonitor(ctx, req.(*SpiderMonitorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_TogglePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePlatformReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).TogglePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_TogglePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).TogglePlatform(ctx, req.(*TogglePlatformReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_UpdatePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlatformReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).UpdatePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_UpdatePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).UpdatePlatform(ctx, req.(*UpdatePlatformReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_RepairContestCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepairContestCellsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).RepairContestCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_RepairContestCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).RepairContestCells(ctx, req.(*RepairContestCellsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_GetPlatformUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetPlatformUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetPlatformUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetPlatformUsers(ctx, req.(*GetPlatformUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Spider_ServiceDesc is the grpc.ServiceDesc for Spider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.core.v1.spider.Spider",
	HandlerType: (*SpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSpider",
			Handler:    _Spider_SetSpider_Handler,
		},
		{
			MethodName: "GetSpider",
			Handler:    _Spider_GetSpider_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Spider_Update_Handler,
		},
		{
			MethodName: "UpdateAll",
			Handler:    _Spider_UpdateAll_Handler,
		},
		{
			MethodName: "PurgeUserData",
			Handler:    _Spider_PurgeUserData_Handler,
		},
		{
			MethodName: "SubmitInventory",
			Handler:    _Spider_SubmitInventory_Handler,
		},
		{
			MethodName: "PurgeSubmitsAndRecrawl",
			Handler:    _Spider_PurgeSubmitsAndRecrawl_Handler,
		},
		{
			MethodName: "EnqueueUserSpider",
			Handler:    _Spider_EnqueueUserSpider_Handler,
		},
		{
			MethodName: "GetSpiderMonitor",
			Handler:    _Spider_GetSpiderMonitor_Handler,
		},
		{
			MethodName: "TogglePlatform",
			Handler:    _Spider_TogglePlatform_Handler,
		},
		{
			MethodName: "UpdatePlatform",
			Handler:    _Spider_UpdatePlatform_Handler,
		},
		{
			MethodName: "RepairContestCells",
			Handler:    _Spider_RepairContestCells_Handler,
		},
		{
			MethodName: "GetPlatformUsers",
			Handler:    _Spider_GetPlatformUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/spider/spider.proto",
}
