// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: core/v1/emergency/emergency.proto

package emergency

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEmergencyActive = "/api.core.v1.emergency.Emergency/Active"
const OperationEmergencyCreate = "/api.core.v1.emergency.Emergency/Create"
const OperationEmergencyDelete = "/api.core.v1.emergency.Emergency/Delete"
const OperationEmergencyList = "/api.core.v1.emergency.Emergency/List"
const OperationEmergencyReorder = "/api.core.v1.emergency.Emergency/Reorder"
const OperationEmergencyUpdate = "/api.core.v1.emergency.Emergency/Update"

type EmergencyHTTPServer interface {
	// Active 当前生效的紧急通知（公开，前端弹窗用）
	Active(context.Context, *ActiveEmergencyReq) (*ActiveEmergencyRes, error)
	// Create 创建紧急通知（站点管理员）
	Create(context.Context, *CreateEmergencyReq) (*CreateEmergencyRes, error)
	// Delete 删除紧急通知（站点管理员）
	Delete(context.Context, *DeleteEmergencyReq) (*DeleteEmergencyRes, error)
	// List 后台分页列表（站点管理员）
	List(context.Context, *ListEmergencyReq) (*ListEmergencyRes, error)
	// Reorder 拖拽排序：按 ids 顺序重写 sortOrder（站点管理员）
	Reorder(context.Context, *ReorderEmergencyReq) (*ReorderEmergencyRes, error)
	// Update 更新紧急通知（站点管理员）
	Update(context.Context, *UpdateEmergencyReq) (*UpdateEmergencyRes, error)
}

func RegisterEmergencyHTTPServer(s *http.Server, srv EmergencyHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/core/emergency/create", _Emergency_Create1_HTTP_Handler(srv))
	r.POST("/v1/core/emergency/update", _Emergency_Update1_HTTP_Handler(srv))
	r.DELETE("/v1/core/emergency/delete", _Emergency_Delete1_HTTP_Handler(srv))
	r.GET("/v1/core/emergency/list", _Emergency_List1_HTTP_Handler(srv))
	r.GET("/v1/core/emergency/active", _Emergency_Active0_HTTP_Handler(srv))
	r.POST("/v1/core/emergency/reorder", _Emergency_Reorder1_HTTP_Handler(srv))
}

func _Emergency_Create1_HTTP_Handler(srv EmergencyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEmergencyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmergencyCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateEmergencyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEmergencyRes)
		return ctx.Result(200, reply)
	}
}

func _Emergency_Update1_HTTP_Handler(srv EmergencyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEmergencyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmergencyUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateEmergencyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEmergencyRes)
		return ctx.Result(200, reply)
	}
}

func _Emergency_Delete1_HTTP_Handler(srv EmergencyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEmergencyReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmergencyDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*DeleteEmergencyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEmergencyRes)
		return ctx.Result(200, reply)
	}
}

func _Emergency_List1_HTTP_Handler(srv EmergencyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEmergencyReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmergencyList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListEmergencyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEmergencyRes)
		return ctx.Result(200, reply)
	}
}

func _Emergency_Active0_HTTP_Handler(srv EmergencyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ActiveEmergencyReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmergencyActive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Active(ctx, req.(*ActiveEmergencyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ActiveEmergencyRes)
		return ctx.Result(200, reply)
	}
}

func _Emergency_Reorder1_HTTP_Handler(srv EmergencyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReorderEmergencyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmergencyReorder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Reorder(ctx, req.(*ReorderEmergencyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReorderEmergencyRes)
		return ctx.Result(200, reply)
	}
}

type EmergencyHTTPClient interface {
	// Active 当前生效的紧急通知（公开，前端弹窗用）
	Active(ctx context.Context, req *ActiveEmergencyReq, opts ...http.CallOption) (rsp *ActiveEmergencyRes, err error)
	// Create 创建紧急通知（站点管理员）
	Create(ctx context.Context, req *CreateEmergencyReq, opts ...http.CallOption) (rsp *CreateEmergencyRes, err error)
	// Delete 删除紧急通知（站点管理员）
	Delete(ctx context.Context, req *DeleteEmergencyReq, opts ...http.CallOption) (rsp *DeleteEmergencyRes, err error)
	// List 后台分页列表（站点管理员）
	List(ctx context.Context, req *ListEmergencyReq, opts ...http.CallOption) (rsp *ListEmergencyRes, err error)
	// Reorder 拖拽排序：按 ids 顺序重写 sortOrder（站点管理员）
	Reorder(ctx context.Context, req *ReorderEmergencyReq, opts ...http.CallOption) (rsp *ReorderEmergencyRes, err error)
	// Update 更新紧急通知（站点管理员）
	Update(ctx context.Context, req *UpdateEmergencyReq, opts ...http.CallOption) (rsp *UpdateEmergencyRes, err error)
}

type EmergencyHTTPClientImpl struct {
	cc *http.Client
}

func NewEmergencyHTTPClient(client *http.Client) EmergencyHTTPClient {
	return &EmergencyHTTPClientImpl{client}
}

// Active 当前生效的紧急通知（公开，前端弹窗用）
func (c *EmergencyHTTPClientImpl) Active(ctx context.Context, in *ActiveEmergencyReq, opts ...http.CallOption) (*ActiveEmergencyRes, error) {
	var out ActiveEmergencyRes
	pattern := "/v1/core/emergency/active"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmergencyActive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Create 创建紧急通知（站点管理员）
func (c *EmergencyHTTPClientImpl) Create(ctx context.Context, in *CreateEmergencyReq, opts ...http.CallOption) (*CreateEmergencyRes, error) {
	var out CreateEmergencyRes
	pattern := "/v1/core/emergency/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmergencyCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete 删除紧急通知（站点管理员）
func (c *EmergencyHTTPClientImpl) Delete(ctx context.Context, in *DeleteEmergencyReq, opts ...http.CallOption) (*DeleteEmergencyRes, error) {
	var out DeleteEmergencyRes
	pattern := "/v1/core/emergency/delete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmergencyDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List 后台分页列表（站点管理员）
func (c *EmergencyHTTPClientImpl) List(ctx context.Context, in *ListEmergencyReq, opts ...http.CallOption) (*ListEmergencyRes, error) {
	var out ListEmergencyRes
	pattern := "/v1/core/emergency/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEmergencyList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Reorder 拖拽排序：按 ids 顺序重写 sortOrder（站点管理员）
func (c *EmergencyHTTPClientImpl) Reorder(ctx context.Context, in *ReorderEmergencyReq, opts ...http.CallOption) (*ReorderEmergencyRes, error) {
	var out ReorderEmergencyRes
	pattern := "/v1/core/emergency/reorder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmergencyReorder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update 更新紧急通知（站点管理员）
func (c *EmergencyHTTPClientImpl) Update(ctx context.Context, in *UpdateEmergencyReq, opts ...http.CallOption) (*UpdateEmergencyRes, error) {
	var out UpdateEmergencyRes
	pattern := "/v1/core/emergency/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEmergencyUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
