// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: core/v1/backup/backup.proto

package backup

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBackupRun = "/api.core.v1.backup.Backup/Run"
const OperationBackupStatus = "/api.core.v1.backup.Backup/Status"

type BackupHTTPServer interface {
	Run(context.Context, *RunBackupRequest) (*RunBackupReply, error)
	Status(context.Context, *GetBackupStatusRequest) (*GetBackupStatusReply, error)
}

func RegisterBackupHTTPServer(s *http.Server, srv BackupHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/core/backup/run", _Backup_Run0_HTTP_Handler(srv))
	r.GET("/v1/core/backup/status", _Backup_Status0_HTTP_Handler(srv))
}

func _Backup_Run0_HTTP_Handler(srv BackupHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunBackupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackupRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Run(ctx, req.(*RunBackupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RunBackupReply)
		return ctx.Result(200, reply)
	}
}

func _Backup_Status0_HTTP_Handler(srv BackupHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBackupStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBackupStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Status(ctx, req.(*GetBackupStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBackupStatusReply)
		return ctx.Result(200, reply)
	}
}

type BackupHTTPClient interface {
	Run(ctx context.Context, req *RunBackupRequest, opts ...http.CallOption) (rsp *RunBackupReply, err error)
	Status(ctx context.Context, req *GetBackupStatusRequest, opts ...http.CallOption) (rsp *GetBackupStatusReply, err error)
}

type BackupHTTPClientImpl struct {
	cc *http.Client
}

func NewBackupHTTPClient(client *http.Client) BackupHTTPClient {
	return &BackupHTTPClientImpl{client}
}

func (c *BackupHTTPClientImpl) Run(ctx context.Context, in *RunBackupRequest, opts ...http.CallOption) (*RunBackupReply, error) {
	var out RunBackupReply
	pattern := "/v1/core/backup/run"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBackupRun))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BackupHTTPClientImpl) Status(ctx context.Context, in *GetBackupStatusRequest, opts ...http.CallOption) (*GetBackupStatusReply, error) {
	var out GetBackupStatusReply
	pattern := "/v1/core/backup/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBackupStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
