// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: user/v1/org/org.proto

package org

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrgAddMember = "/api.user.v1.org.Org/AddMember"
const OperationOrgCreate = "/api.user.v1.org.Org/Create"
const OperationOrgDelete = "/api.user.v1.org.Org/Delete"
const OperationOrgDiscover = "/api.user.v1.org.Org/Discover"
const OperationOrgGet = "/api.user.v1.org.Org/Get"
const OperationOrgInvite = "/api.user.v1.org.Org/Invite"
const OperationOrgInviteCancel = "/api.user.v1.org.Org/InviteCancel"
const OperationOrgInvitePreview = "/api.user.v1.org.Org/InvitePreview"
const OperationOrgInviteReview = "/api.user.v1.org.Org/InviteReview"
const OperationOrgInviteRotate = "/api.user.v1.org.Org/InviteRotate"
const OperationOrgInviteUser = "/api.user.v1.org.Org/InviteUser"
const OperationOrgInvites = "/api.user.v1.org.Org/Invites"
const OperationOrgJoin = "/api.user.v1.org.Org/Join"
const OperationOrgJoinRequests = "/api.user.v1.org.Org/JoinRequests"
const OperationOrgJoinReview = "/api.user.v1.org.Org/JoinReview"
const OperationOrgLeave = "/api.user.v1.org.Org/Leave"
const OperationOrgList = "/api.user.v1.org.Org/List"
const OperationOrgMemberIds = "/api.user.v1.org.Org/MemberIds"
const OperationOrgMembers = "/api.user.v1.org.Org/Members"
const OperationOrgRemoveMember = "/api.user.v1.org.Org/RemoveMember"
const OperationOrgScopeList = "/api.user.v1.org.Org/ScopeList"
const OperationOrgScopeSet = "/api.user.v1.org.Org/ScopeSet"
const OperationOrgSetDisplayName = "/api.user.v1.org.Org/SetDisplayName"
const OperationOrgSetRole = "/api.user.v1.org.Org/SetRole"
const OperationOrgSetSiteAdmin = "/api.user.v1.org.Org/SetSiteAdmin"
const OperationOrgSquadCreate = "/api.user.v1.org.Org/SquadCreate"
const OperationOrgSquadDelete = "/api.user.v1.org.Org/SquadDelete"
const OperationOrgSquadList = "/api.user.v1.org.Org/SquadList"
const OperationOrgSquadMemberSet = "/api.user.v1.org.Org/SquadMemberSet"
const OperationOrgSquadMembers = "/api.user.v1.org.Org/SquadMembers"
const OperationOrgSquadUpdate = "/api.user.v1.org.Org/SquadUpdate"
const OperationOrgSwitch = "/api.user.v1.org.Org/Switch"
const OperationOrgUpdate = "/api.user.v1.org.Org/Update"

type OrgHTTPServer interface {
	AddMember(context.Context, *AddMemberReq) (*AddMemberRes, error)
	Create(context.Context, *CreateReq) (*CreateRes, error)
	Delete(context.Context, *DeleteReq) (*DeleteRes, error)
	// Discover 组织广场（公开：仅名/logo/人数）
	Discover(context.Context, *DiscoverReq) (*DiscoverRes, error)
	Get(context.Context, *GetReq) (*GetRes, error)
	Invite(context.Context, *InviteReq) (*InviteRes, error)
	// InviteCancel 组织侧撤回未决邀请
	InviteCancel(context.Context, *InviteCancelReq) (*InviteCancelRes, error)
	// InvitePreview 公开：按识别码预览组织欢迎信息（不含敏感配置）
	InvitePreview(context.Context, *InvitePreviewReq) (*InvitePreviewRes, error)
	// InviteReview 被邀请人接受/拒绝
	InviteReview(context.Context, *InviteReviewReq) (*InviteReviewRes, error)
	InviteRotate(context.Context, *InviteRotateReq) (*InviteRotateRes, error)
	// InviteUser 组织管理员邀请加入：需被邀请人同意后才成为成员（站管直接加人请用 AddMember）
	InviteUser(context.Context, *InviteUserReq) (*InviteUserRes, error)
	// Invites 邀请列表：带 orgId（且有 org.member.add 权限）返回组织未决邀请；否则返回我收到的邀请
	Invites(context.Context, *InvitesReq) (*InvitesRes, error)
	// Join 按团队识别码加入
	Join(context.Context, *JoinReq) (*JoinRes, error)
	JoinRequests(context.Context, *JoinRequestsReq) (*JoinRequestsRes, error)
	JoinReview(context.Context, *JoinReviewReq) (*JoinReviewRes, error)
	Leave(context.Context, *LeaveReq) (*LeaveRes, error)
	// List 我的组织列表（mine=0 时返回我加入的组织；all=1 且具站点权限时返回全部）
	List(context.Context, *ListReq) (*ListRes, error)
	// MemberIds 组织成员 id 列表（可选按 groupId / squadId 过滤）
	MemberIds(context.Context, *MemberIdsReq) (*MemberIdsRes, error)
	Members(context.Context, *MembersReq) (*MembersRes, error)
	RemoveMember(context.Context, *RemoveMemberReq) (*RemoveMemberRes, error)
	// ScopeList 用户的管理范围（组长→分组 / 队长→分队）
	ScopeList(context.Context, *ScopeListReq) (*ScopeListRes, error)
	// ScopeSet 仅组织管理员/站管手动覆盖范围（组长/队长范围由任命决定）
	ScopeSet(context.Context, *ScopeSetReq) (*ScopeSetRes, error)
	SetDisplayName(context.Context, *SetDisplayNameReq) (*SetDisplayNameRes, error)
	SetRole(context.Context, *SetRoleReq) (*SetRoleRes, error)
	// SetSiteAdmin 站点管理员任命/撤销（站点级）
	SetSiteAdmin(context.Context, *SetSiteAdminReq) (*SetSiteAdminRes, error)
	SquadCreate(context.Context, *SquadCreateReq) (*SquadCreateRes, error)
	SquadDelete(context.Context, *SquadDeleteReq) (*SquadDeleteRes, error)
	SquadList(context.Context, *SquadListReq) (*SquadListRes, error)
	// SquadMemberSet in=true 加入分队 / false 移出
	SquadMemberSet(context.Context, *SquadMemberSetReq) (*SquadMemberSetRes, error)
	SquadMembers(context.Context, *SquadMembersReq) (*SquadMembersRes, error)
	SquadUpdate(context.Context, *SquadUpdateReq) (*SquadUpdateRes, error)
	// Switch 切换当前组织（重签 JWT + 写会话 cookie）
	Switch(context.Context, *SwitchReq) (*SwitchRes, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
}

func RegisterOrgHTTPServer(s *http.Server, srv OrgHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/user/org/list", _Org_List6_HTTP_Handler(srv))
	r.GET("/v1/user/org/discover", _Org_Discover0_HTTP_Handler(srv))
	r.GET("/v1/user/org/get", _Org_Get4_HTTP_Handler(srv))
	r.POST("/v1/user/org/create", _Org_Create4_HTTP_Handler(srv))
	r.POST("/v1/user/org/update", _Org_Update5_HTTP_Handler(srv))
	r.POST("/v1/user/org/delete", _Org_Delete4_HTTP_Handler(srv))
	r.POST("/v1/user/org/switch", _Org_Switch0_HTTP_Handler(srv))
	r.POST("/v1/user/org/join", _Org_Join0_HTTP_Handler(srv))
	r.POST("/v1/user/org/leave", _Org_Leave0_HTTP_Handler(srv))
	r.GET("/v1/user/org/members", _Org_Members0_HTTP_Handler(srv))
	r.POST("/v1/user/org/members/set-role", _Org_SetRole0_HTTP_Handler(srv))
	r.POST("/v1/user/org/members/remove", _Org_RemoveMember0_HTTP_Handler(srv))
	r.POST("/v1/user/org/members/add", _Org_AddMember0_HTTP_Handler(srv))
	r.POST("/v1/user/org/members/invite", _Org_InviteUser0_HTTP_Handler(srv))
	r.GET("/v1/user/org/invites", _Org_Invites0_HTTP_Handler(srv))
	r.POST("/v1/user/org/invites/review", _Org_InviteReview0_HTTP_Handler(srv))
	r.POST("/v1/user/org/invites/cancel", _Org_InviteCancel0_HTTP_Handler(srv))
	r.POST("/v1/user/org/members/set-display-name", _Org_SetDisplayName0_HTTP_Handler(srv))
	r.GET("/v1/user/org/member-ids", _Org_MemberIds0_HTTP_Handler(srv))
	r.GET("/v1/user/org/invite", _Org_Invite0_HTTP_Handler(srv))
	r.GET("/v1/user/org/invite/preview", _Org_InvitePreview0_HTTP_Handler(srv))
	r.POST("/v1/user/org/invite/rotate", _Org_InviteRotate0_HTTP_Handler(srv))
	r.GET("/v1/user/org/join-requests", _Org_JoinRequests0_HTTP_Handler(srv))
	r.POST("/v1/user/org/join-requests/review", _Org_JoinReview0_HTTP_Handler(srv))
	r.POST("/v1/user/platform/set-site-admin", _Org_SetSiteAdmin0_HTTP_Handler(srv))
	r.GET("/v1/user/org/squads", _Org_SquadList0_HTTP_Handler(srv))
	r.POST("/v1/user/org/squads/create", _Org_SquadCreate0_HTTP_Handler(srv))
	r.POST("/v1/user/org/squads/update", _Org_SquadUpdate0_HTTP_Handler(srv))
	r.POST("/v1/user/org/squads/delete", _Org_SquadDelete0_HTTP_Handler(srv))
	r.GET("/v1/user/org/squads/members", _Org_SquadMembers0_HTTP_Handler(srv))
	r.POST("/v1/user/org/squads/members/set", _Org_SquadMemberSet0_HTTP_Handler(srv))
	r.GET("/v1/user/org/scopes", _Org_ScopeList0_HTTP_Handler(srv))
	r.POST("/v1/user/org/scopes/set", _Org_ScopeSet0_HTTP_Handler(srv))
}

func _Org_List6_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Discover0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DiscoverReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgDiscover)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Discover(ctx, req.(*DiscoverReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DiscoverRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Get4_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Create4_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Update5_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Delete4_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*DeleteReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Switch0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SwitchReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSwitch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Switch(ctx, req.(*SwitchReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SwitchRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Join0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JoinReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgJoin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Join(ctx, req.(*JoinReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JoinRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Leave0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LeaveReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgLeave)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Leave(ctx, req.(*LeaveReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LeaveRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Members0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MembersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Members(ctx, req.(*MembersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MembersRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SetRole0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetRoleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSetRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetRole(ctx, req.(*SetRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetRoleRes)
		return ctx.Result(200, reply)
	}
}

func _Org_RemoveMember0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveMemberReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgRemoveMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveMember(ctx, req.(*RemoveMemberReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveMemberRes)
		return ctx.Result(200, reply)
	}
}

func _Org_AddMember0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddMemberReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgAddMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddMember(ctx, req.(*AddMemberReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddMemberRes)
		return ctx.Result(200, reply)
	}
}

func _Org_InviteUser0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InviteUserReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInviteUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InviteUser(ctx, req.(*InviteUserReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InviteUserRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Invites0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InvitesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInvites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Invites(ctx, req.(*InvitesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InvitesRes)
		return ctx.Result(200, reply)
	}
}

func _Org_InviteReview0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InviteReviewReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInviteReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InviteReview(ctx, req.(*InviteReviewReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InviteReviewRes)
		return ctx.Result(200, reply)
	}
}

func _Org_InviteCancel0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InviteCancelReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInviteCancel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InviteCancel(ctx, req.(*InviteCancelReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InviteCancelRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SetDisplayName0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetDisplayNameReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSetDisplayName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDisplayName(ctx, req.(*SetDisplayNameReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetDisplayNameRes)
		return ctx.Result(200, reply)
	}
}

func _Org_MemberIds0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MemberIdsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgMemberIds)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MemberIds(ctx, req.(*MemberIdsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemberIdsRes)
		return ctx.Result(200, reply)
	}
}

func _Org_Invite0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InviteReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInvite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Invite(ctx, req.(*InviteReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InviteRes)
		return ctx.Result(200, reply)
	}
}

func _Org_InvitePreview0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InvitePreviewReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInvitePreview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InvitePreview(ctx, req.(*InvitePreviewReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InvitePreviewRes)
		return ctx.Result(200, reply)
	}
}

func _Org_InviteRotate0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InviteRotateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgInviteRotate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InviteRotate(ctx, req.(*InviteRotateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InviteRotateRes)
		return ctx.Result(200, reply)
	}
}

func _Org_JoinRequests0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JoinRequestsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgJoinRequests)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JoinRequests(ctx, req.(*JoinRequestsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JoinRequestsRes)
		return ctx.Result(200, reply)
	}
}

func _Org_JoinReview0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JoinReviewReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgJoinReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JoinReview(ctx, req.(*JoinReviewReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JoinReviewRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SetSiteAdmin0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetSiteAdminReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSetSiteAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetSiteAdmin(ctx, req.(*SetSiteAdminReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetSiteAdminRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SquadList0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SquadListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSquadList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SquadList(ctx, req.(*SquadListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SquadListRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SquadCreate0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SquadCreateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSquadCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SquadCreate(ctx, req.(*SquadCreateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SquadCreateRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SquadUpdate0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SquadUpdateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSquadUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SquadUpdate(ctx, req.(*SquadUpdateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SquadUpdateRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SquadDelete0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SquadDeleteReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSquadDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SquadDelete(ctx, req.(*SquadDeleteReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SquadDeleteRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SquadMembers0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SquadMembersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSquadMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SquadMembers(ctx, req.(*SquadMembersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SquadMembersRes)
		return ctx.Result(200, reply)
	}
}

func _Org_SquadMemberSet0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SquadMemberSetReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgSquadMemberSet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SquadMemberSet(ctx, req.(*SquadMemberSetReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SquadMemberSetRes)
		return ctx.Result(200, reply)
	}
}

func _Org_ScopeList0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScopeListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgScopeList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ScopeList(ctx, req.(*ScopeListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScopeListRes)
		return ctx.Result(200, reply)
	}
}

func _Org_ScopeSet0_HTTP_Handler(srv OrgHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScopeSetReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgScopeSet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ScopeSet(ctx, req.(*ScopeSetReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScopeSetRes)
		return ctx.Result(200, reply)
	}
}

type OrgHTTPClient interface {
	AddMember(ctx context.Context, req *AddMemberReq, opts ...http.CallOption) (rsp *AddMemberRes, err error)
	Create(ctx context.Context, req *CreateReq, opts ...http.CallOption) (rsp *CreateRes, err error)
	Delete(ctx context.Context, req *DeleteReq, opts ...http.CallOption) (rsp *DeleteRes, err error)
	// Discover 组织广场（公开：仅名/logo/人数）
	Discover(ctx context.Context, req *DiscoverReq, opts ...http.CallOption) (rsp *DiscoverRes, err error)
	Get(ctx context.Context, req *GetReq, opts ...http.CallOption) (rsp *GetRes, err error)
	Invite(ctx context.Context, req *InviteReq, opts ...http.CallOption) (rsp *InviteRes, err error)
	// InviteCancel 组织侧撤回未决邀请
	InviteCancel(ctx context.Context, req *InviteCancelReq, opts ...http.CallOption) (rsp *InviteCancelRes, err error)
	// InvitePreview 公开：按识别码预览组织欢迎信息（不含敏感配置）
	InvitePreview(ctx context.Context, req *InvitePreviewReq, opts ...http.CallOption) (rsp *InvitePreviewRes, err error)
	// InviteReview 被邀请人接受/拒绝
	InviteReview(ctx context.Context, req *InviteReviewReq, opts ...http.CallOption) (rsp *InviteReviewRes, err error)
	InviteRotate(ctx context.Context, req *InviteRotateReq, opts ...http.CallOption) (rsp *InviteRotateRes, err error)
	// InviteUser 组织管理员邀请加入：需被邀请人同意后才成为成员（站管直接加人请用 AddMember）
	InviteUser(ctx context.Context, req *InviteUserReq, opts ...http.CallOption) (rsp *InviteUserRes, err error)
	// Invites 邀请列表：带 orgId（且有 org.member.add 权限）返回组织未决邀请；否则返回我收到的邀请
	Invites(ctx context.Context, req *InvitesReq, opts ...http.CallOption) (rsp *InvitesRes, err error)
	// Join 按团队识别码加入
	Join(ctx context.Context, req *JoinReq, opts ...http.CallOption) (rsp *JoinRes, err error)
	JoinRequests(ctx context.Context, req *JoinRequestsReq, opts ...http.CallOption) (rsp *JoinRequestsRes, err error)
	JoinReview(ctx context.Context, req *JoinReviewReq, opts ...http.CallOption) (rsp *JoinReviewRes, err error)
	Leave(ctx context.Context, req *LeaveReq, opts ...http.CallOption) (rsp *LeaveRes, err error)
	// List 我的组织列表（mine=0 时返回我加入的组织；all=1 且具站点权限时返回全部）
	List(ctx context.Context, req *ListReq, opts ...http.CallOption) (rsp *ListRes, err error)
	// MemberIds 组织成员 id 列表（可选按 groupId / squadId 过滤）
	MemberIds(ctx context.Context, req *MemberIdsReq, opts ...http.CallOption) (rsp *MemberIdsRes, err error)
	Members(ctx context.Context, req *MembersReq, opts ...http.CallOption) (rsp *MembersRes, err error)
	RemoveMember(ctx context.Context, req *RemoveMemberReq, opts ...http.CallOption) (rsp *RemoveMemberRes, err error)
	// ScopeList 用户的管理范围（组长→分组 / 队长→分队）
	ScopeList(ctx context.Context, req *ScopeListReq, opts ...http.CallOption) (rsp *ScopeListRes, err error)
	// ScopeSet 仅组织管理员/站管手动覆盖范围（组长/队长范围由任命决定）
	ScopeSet(ctx context.Context, req *ScopeSetReq, opts ...http.CallOption) (rsp *ScopeSetRes, err error)
	SetDisplayName(ctx context.Context, req *SetDisplayNameReq, opts ...http.CallOption) (rsp *SetDisplayNameRes, err error)
	SetRole(ctx context.Context, req *SetRoleReq, opts ...http.CallOption) (rsp *SetRoleRes, err error)
	// SetSiteAdmin 站点管理员任命/撤销（站点级）
	SetSiteAdmin(ctx context.Context, req *SetSiteAdminReq, opts ...http.CallOption) (rsp *SetSiteAdminRes, err error)
	SquadCreate(ctx context.Context, req *SquadCreateReq, opts ...http.CallOption) (rsp *SquadCreateRes, err error)
	SquadDelete(ctx context.Context, req *SquadDeleteReq, opts ...http.CallOption) (rsp *SquadDeleteRes, err error)
	SquadList(ctx context.Context, req *SquadListReq, opts ...http.CallOption) (rsp *SquadListRes, err error)
	// SquadMemberSet in=true 加入分队 / false 移出
	SquadMemberSet(ctx context.Context, req *SquadMemberSetReq, opts ...http.CallOption) (rsp *SquadMemberSetRes, err error)
	SquadMembers(ctx context.Context, req *SquadMembersReq, opts ...http.CallOption) (rsp *SquadMembersRes, err error)
	SquadUpdate(ctx context.Context, req *SquadUpdateReq, opts ...http.CallOption) (rsp *SquadUpdateRes, err error)
	// Switch 切换当前组织（重签 JWT + 写会话 cookie）
	Switch(ctx context.Context, req *SwitchReq, opts ...http.CallOption) (rsp *SwitchRes, err error)
	Update(ctx context.Context, req *UpdateReq, opts ...http.CallOption) (rsp *UpdateRes, err error)
}

type OrgHTTPClientImpl struct {
	cc *http.Client
}

func NewOrgHTTPClient(client *http.Client) OrgHTTPClient {
	return &OrgHTTPClientImpl{client}
}

func (c *OrgHTTPClientImpl) AddMember(ctx context.Context, in *AddMemberReq, opts ...http.CallOption) (*AddMemberRes, error) {
	var out AddMemberRes
	pattern := "/v1/user/org/members/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgAddMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Create(ctx context.Context, in *CreateReq, opts ...http.CallOption) (*CreateRes, error) {
	var out CreateRes
	pattern := "/v1/user/org/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Delete(ctx context.Context, in *DeleteReq, opts ...http.CallOption) (*DeleteRes, error) {
	var out DeleteRes
	pattern := "/v1/user/org/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Discover 组织广场（公开：仅名/logo/人数）
func (c *OrgHTTPClientImpl) Discover(ctx context.Context, in *DiscoverReq, opts ...http.CallOption) (*DiscoverRes, error) {
	var out DiscoverRes
	pattern := "/v1/user/org/discover"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgDiscover))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Get(ctx context.Context, in *GetReq, opts ...http.CallOption) (*GetRes, error) {
	var out GetRes
	pattern := "/v1/user/org/get"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Invite(ctx context.Context, in *InviteReq, opts ...http.CallOption) (*InviteRes, error) {
	var out InviteRes
	pattern := "/v1/user/org/invite"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgInvite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InviteCancel 组织侧撤回未决邀请
func (c *OrgHTTPClientImpl) InviteCancel(ctx context.Context, in *InviteCancelReq, opts ...http.CallOption) (*InviteCancelRes, error) {
	var out InviteCancelRes
	pattern := "/v1/user/org/invites/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgInviteCancel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InvitePreview 公开：按识别码预览组织欢迎信息（不含敏感配置）
func (c *OrgHTTPClientImpl) InvitePreview(ctx context.Context, in *InvitePreviewReq, opts ...http.CallOption) (*InvitePreviewRes, error) {
	var out InvitePreviewRes
	pattern := "/v1/user/org/invite/preview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgInvitePreview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InviteReview 被邀请人接受/拒绝
func (c *OrgHTTPClientImpl) InviteReview(ctx context.Context, in *InviteReviewReq, opts ...http.CallOption) (*InviteReviewRes, error) {
	var out InviteReviewRes
	pattern := "/v1/user/org/invites/review"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgInviteReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) InviteRotate(ctx context.Context, in *InviteRotateReq, opts ...http.CallOption) (*InviteRotateRes, error) {
	var out InviteRotateRes
	pattern := "/v1/user/org/invite/rotate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgInviteRotate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InviteUser 组织管理员邀请加入：需被邀请人同意后才成为成员（站管直接加人请用 AddMember）
func (c *OrgHTTPClientImpl) InviteUser(ctx context.Context, in *InviteUserReq, opts ...http.CallOption) (*InviteUserRes, error) {
	var out InviteUserRes
	pattern := "/v1/user/org/members/invite"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgInviteUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Invites 邀请列表：带 orgId（且有 org.member.add 权限）返回组织未决邀请；否则返回我收到的邀请
func (c *OrgHTTPClientImpl) Invites(ctx context.Context, in *InvitesReq, opts ...http.CallOption) (*InvitesRes, error) {
	var out InvitesRes
	pattern := "/v1/user/org/invites"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgInvites))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Join 按团队识别码加入
func (c *OrgHTTPClientImpl) Join(ctx context.Context, in *JoinReq, opts ...http.CallOption) (*JoinRes, error) {
	var out JoinRes
	pattern := "/v1/user/org/join"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgJoin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) JoinRequests(ctx context.Context, in *JoinRequestsReq, opts ...http.CallOption) (*JoinRequestsRes, error) {
	var out JoinRequestsRes
	pattern := "/v1/user/org/join-requests"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgJoinRequests))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) JoinReview(ctx context.Context, in *JoinReviewReq, opts ...http.CallOption) (*JoinReviewRes, error) {
	var out JoinReviewRes
	pattern := "/v1/user/org/join-requests/review"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgJoinReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Leave(ctx context.Context, in *LeaveReq, opts ...http.CallOption) (*LeaveRes, error) {
	var out LeaveRes
	pattern := "/v1/user/org/leave"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgLeave))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List 我的组织列表（mine=0 时返回我加入的组织；all=1 且具站点权限时返回全部）
func (c *OrgHTTPClientImpl) List(ctx context.Context, in *ListReq, opts ...http.CallOption) (*ListRes, error) {
	var out ListRes
	pattern := "/v1/user/org/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MemberIds 组织成员 id 列表（可选按 groupId / squadId 过滤）
func (c *OrgHTTPClientImpl) MemberIds(ctx context.Context, in *MemberIdsReq, opts ...http.CallOption) (*MemberIdsRes, error) {
	var out MemberIdsRes
	pattern := "/v1/user/org/member-ids"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgMemberIds))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Members(ctx context.Context, in *MembersReq, opts ...http.CallOption) (*MembersRes, error) {
	var out MembersRes
	pattern := "/v1/user/org/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...http.CallOption) (*RemoveMemberRes, error) {
	var out RemoveMemberRes
	pattern := "/v1/user/org/members/remove"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgRemoveMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ScopeList 用户的管理范围（组长→分组 / 队长→分队）
func (c *OrgHTTPClientImpl) ScopeList(ctx context.Context, in *ScopeListReq, opts ...http.CallOption) (*ScopeListRes, error) {
	var out ScopeListRes
	pattern := "/v1/user/org/scopes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgScopeList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ScopeSet 仅组织管理员/站管手动覆盖范围（组长/队长范围由任命决定）
func (c *OrgHTTPClientImpl) ScopeSet(ctx context.Context, in *ScopeSetReq, opts ...http.CallOption) (*ScopeSetRes, error) {
	var out ScopeSetRes
	pattern := "/v1/user/org/scopes/set"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgScopeSet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SetDisplayName(ctx context.Context, in *SetDisplayNameReq, opts ...http.CallOption) (*SetDisplayNameRes, error) {
	var out SetDisplayNameRes
	pattern := "/v1/user/org/members/set-display-name"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSetDisplayName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SetRole(ctx context.Context, in *SetRoleReq, opts ...http.CallOption) (*SetRoleRes, error) {
	var out SetRoleRes
	pattern := "/v1/user/org/members/set-role"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSetRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetSiteAdmin 站点管理员任命/撤销（站点级）
func (c *OrgHTTPClientImpl) SetSiteAdmin(ctx context.Context, in *SetSiteAdminReq, opts ...http.CallOption) (*SetSiteAdminRes, error) {
	var out SetSiteAdminRes
	pattern := "/v1/user/platform/set-site-admin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSetSiteAdmin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SquadCreate(ctx context.Context, in *SquadCreateReq, opts ...http.CallOption) (*SquadCreateRes, error) {
	var out SquadCreateRes
	pattern := "/v1/user/org/squads/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSquadCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SquadDelete(ctx context.Context, in *SquadDeleteReq, opts ...http.CallOption) (*SquadDeleteRes, error) {
	var out SquadDeleteRes
	pattern := "/v1/user/org/squads/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSquadDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SquadList(ctx context.Context, in *SquadListReq, opts ...http.CallOption) (*SquadListRes, error) {
	var out SquadListRes
	pattern := "/v1/user/org/squads"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgSquadList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SquadMemberSet in=true 加入分队 / false 移出
func (c *OrgHTTPClientImpl) SquadMemberSet(ctx context.Context, in *SquadMemberSetReq, opts ...http.CallOption) (*SquadMemberSetRes, error) {
	var out SquadMemberSetRes
	pattern := "/v1/user/org/squads/members/set"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSquadMemberSet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SquadMembers(ctx context.Context, in *SquadMembersReq, opts ...http.CallOption) (*SquadMembersRes, error) {
	var out SquadMembersRes
	pattern := "/v1/user/org/squads/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrgSquadMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) SquadUpdate(ctx context.Context, in *SquadUpdateReq, opts ...http.CallOption) (*SquadUpdateRes, error) {
	var out SquadUpdateRes
	pattern := "/v1/user/org/squads/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSquadUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Switch 切换当前组织（重签 JWT + 写会话 cookie）
func (c *OrgHTTPClientImpl) Switch(ctx context.Context, in *SwitchReq, opts ...http.CallOption) (*SwitchRes, error) {
	var out SwitchRes
	pattern := "/v1/user/org/switch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgSwitch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgHTTPClientImpl) Update(ctx context.Context, in *UpdateReq, opts ...http.CallOption) (*UpdateRes, error) {
	var out UpdateRes
	pattern := "/v1/user/org/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrgUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
