// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: user/v1/ticket/ticket.proto

package ticket

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTicketServiceCreate = "/api.user.v1.ticket.TicketService/Create"
const OperationTicketServiceCreateMessage = "/api.user.v1.ticket.TicketService/CreateMessage"
const OperationTicketServiceGet = "/api.user.v1.ticket.TicketService/Get"
const OperationTicketServiceGetMessages = "/api.user.v1.ticket.TicketService/GetMessages"
const OperationTicketServiceList = "/api.user.v1.ticket.TicketService/List"
const OperationTicketServicePatchStatus = "/api.user.v1.ticket.TicketService/PatchStatus"

type TicketServiceHTTPServer interface {
	// Create 创建工单
	Create(context.Context, *CreateTicketReq) (*CreateTicketRes, error)
	// CreateMessage 补充消息
	CreateMessage(context.Context, *CreateMessageReq) (*CreateMessageRes, error)
	// Get 工单详情
	Get(context.Context, *GetTicketReq) (*GetTicketRes, error)
	// GetMessages 消息列表（增量：after_sequence 之后的 public 消息）
	GetMessages(context.Context, *GetMessagesReq) (*GetMessagesRes, error)
	// List 工单列表（cursor 分页）
	List(context.Context, *ListTicketsReq) (*ListTicketsRes, error)
	// PatchStatus 用户修改工单状态（pending_agent|pending_customer → resolved|closed）
	PatchStatus(context.Context, *PatchStatusReq) (*PatchStatusRes, error)
}

func RegisterTicketServiceHTTPServer(s *http.Server, srv TicketServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/user/tickets", _TicketService_List7_HTTP_Handler(srv))
	r.GET("/v1/user/tickets/{ticket_id}", _TicketService_Get5_HTTP_Handler(srv))
	r.GET("/v1/user/tickets/{ticket_id}/messages", _TicketService_GetMessages0_HTTP_Handler(srv))
	r.POST("/v1/user/tickets", _TicketService_Create6_HTTP_Handler(srv))
	r.POST("/v1/user/tickets/{ticket_id}/messages", _TicketService_CreateMessage0_HTTP_Handler(srv))
	r.PATCH("/v1/user/tickets/{ticket_id}/status", _TicketService_PatchStatus0_HTTP_Handler(srv))
}

func _TicketService_List7_HTTP_Handler(srv TicketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTicketsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListTicketsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTicketsRes)
		return ctx.Result(200, reply)
	}
}

func _TicketService_Get5_HTTP_Handler(srv TicketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTicketReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketServiceGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetTicketReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTicketRes)
		return ctx.Result(200, reply)
	}
}

func _TicketService_GetMessages0_HTTP_Handler(srv TicketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMessagesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketServiceGetMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMessages(ctx, req.(*GetMessagesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMessagesRes)
		return ctx.Result(200, reply)
	}
}

func _TicketService_Create6_HTTP_Handler(srv TicketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTicketReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketServiceCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateTicketReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTicketRes)
		return ctx.Result(200, reply)
	}
}

func _TicketService_CreateMessage0_HTTP_Handler(srv TicketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMessageReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketServiceCreateMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMessage(ctx, req.(*CreateMessageReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateMessageRes)
		return ctx.Result(200, reply)
	}
}

func _TicketService_PatchStatus0_HTTP_Handler(srv TicketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PatchStatusReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketServicePatchStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PatchStatus(ctx, req.(*PatchStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PatchStatusRes)
		return ctx.Result(200, reply)
	}
}

type TicketServiceHTTPClient interface {
	// Create 创建工单
	Create(ctx context.Context, req *CreateTicketReq, opts ...http.CallOption) (rsp *CreateTicketRes, err error)
	// CreateMessage 补充消息
	CreateMessage(ctx context.Context, req *CreateMessageReq, opts ...http.CallOption) (rsp *CreateMessageRes, err error)
	// Get 工单详情
	Get(ctx context.Context, req *GetTicketReq, opts ...http.CallOption) (rsp *GetTicketRes, err error)
	// GetMessages 消息列表（增量：after_sequence 之后的 public 消息）
	GetMessages(ctx context.Context, req *GetMessagesReq, opts ...http.CallOption) (rsp *GetMessagesRes, err error)
	// List 工单列表（cursor 分页）
	List(ctx context.Context, req *ListTicketsReq, opts ...http.CallOption) (rsp *ListTicketsRes, err error)
	// PatchStatus 用户修改工单状态（pending_agent|pending_customer → resolved|closed）
	PatchStatus(ctx context.Context, req *PatchStatusReq, opts ...http.CallOption) (rsp *PatchStatusRes, err error)
}

type TicketServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTicketServiceHTTPClient(client *http.Client) TicketServiceHTTPClient {
	return &TicketServiceHTTPClientImpl{client}
}

// Create 创建工单
func (c *TicketServiceHTTPClientImpl) Create(ctx context.Context, in *CreateTicketReq, opts ...http.CallOption) (*CreateTicketRes, error) {
	var out CreateTicketRes
	pattern := "/v1/user/tickets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTicketServiceCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateMessage 补充消息
func (c *TicketServiceHTTPClientImpl) CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...http.CallOption) (*CreateMessageRes, error) {
	var out CreateMessageRes
	pattern := "/v1/user/tickets/{ticket_id}/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTicketServiceCreateMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get 工单详情
func (c *TicketServiceHTTPClientImpl) Get(ctx context.Context, in *GetTicketReq, opts ...http.CallOption) (*GetTicketRes, error) {
	var out GetTicketRes
	pattern := "/v1/user/tickets/{ticket_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTicketServiceGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMessages 消息列表（增量：after_sequence 之后的 public 消息）
func (c *TicketServiceHTTPClientImpl) GetMessages(ctx context.Context, in *GetMessagesReq, opts ...http.CallOption) (*GetMessagesRes, error) {
	var out GetMessagesRes
	pattern := "/v1/user/tickets/{ticket_id}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTicketServiceGetMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List 工单列表（cursor 分页）
func (c *TicketServiceHTTPClientImpl) List(ctx context.Context, in *ListTicketsReq, opts ...http.CallOption) (*ListTicketsRes, error) {
	var out ListTicketsRes
	pattern := "/v1/user/tickets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTicketServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PatchStatus 用户修改工单状态（pending_agent|pending_customer → resolved|closed）
func (c *TicketServiceHTTPClientImpl) PatchStatus(ctx context.Context, in *PatchStatusReq, opts ...http.CallOption) (*PatchStatusRes, error) {
	var out PatchStatusRes
	pattern := "/v1/user/tickets/{ticket_id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTicketServicePatchStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
