// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user/v1/ticket/ticket.proto

package ticket

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 工单（时间字段统一 unix 秒）
type Ticket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketNumber    int64                  `protobuf:"varint,2,opt,name=ticket_number,json=ticketNumber,proto3" json:"ticket_number,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority        string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	AwaitingActor   string                 `protobuf:"bytes,6,opt,name=awaiting_actor,json=awaitingActor,proto3" json:"awaiting_actor,omitempty"`
	LatestMessageAt int64                  `protobuf:"varint,7,opt,name=latest_message_at,json=latestMessageAt,proto3" json:"latest_message_at,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetTicketNumber() int64 {
	if x != nil {
		return x.TicketNumber
	}
	return 0
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ticket) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Ticket) GetAwaitingActor() string {
	if x != nil {
		return x.AwaitingActor
	}
	return ""
}

func (x *Ticket) GetLatestMessageAt() int64 {
	if x != nil {
		return x.LatestMessageAt
	}
	return 0
}

func (x *Ticket) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Ticket) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 工单消息
type TicketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SequenceNo    int64                  `protobuf:"varint,2,opt,name=sequence_no,json=sequenceNo,proto3" json:"sequence_no,omitempty"`
	SenderType    string                 `protobuf:"bytes,3,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	SentAt        int64                  `protobuf:"varint,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketMessage) Reset() {
	*x = TicketMessage{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketMessage) ProtoMessage() {}

func (x *TicketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketMessage.ProtoReflect.Descriptor instead.
func (*TicketMessage) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *TicketMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketMessage) GetSequenceNo() int64 {
	if x != nil {
		return x.SequenceNo
	}
	return 0
}

func (x *TicketMessage) GetSenderType() string {
	if x != nil {
		return x.SenderType
	}
	return ""
}

func (x *TicketMessage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TicketMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TicketMessage) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type CreateTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketReq) Reset() {
	*x = CreateTicketReq{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketReq) ProtoMessage() {}

func (x *CreateTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketReq.ProtoReflect.Descriptor instead.
func (*CreateTicketReq) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTicketReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateTicketRes struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ticket  *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// message_info 命名避开 protobuf 保留关键字 message
	MessageInfo   *TicketMessage `protobuf:"bytes,4,opt,name=message_info,json=messageInfo,proto3" json:"message_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRes) Reset() {
	*x = CreateTicketRes{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRes) ProtoMessage() {}

func (x *CreateTicketRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRes.ProtoReflect.Descriptor instead.
func (*CreateTicketRes) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTicketRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTicketRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTicketRes) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *CreateTicketRes) GetMessageInfo() *TicketMessage {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

type CreateMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageReq) Reset() {
	*x = CreateMessageReq{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageReq) ProtoMessage() {}

func (x *CreateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageReq.ProtoReflect.Descriptor instead.
func (*CreateMessageReq) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMessageReq) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CreateMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMessageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageInfo   *TicketMessage         `protobuf:"bytes,3,opt,name=message_info,json=messageInfo,proto3" json:"message_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRes) Reset() {
	*x = CreateMessageRes{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRes) ProtoMessage() {}

func (x *CreateMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRes.ProtoReflect.Descriptor instead.
func (*CreateMessageRes) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMessageRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateMessageRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMessageRes) GetMessageInfo() *TicketMessage {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

type PatchStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchStatusReq) Reset() {
	*x = PatchStatusReq{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchStatusReq) ProtoMessage() {}

func (x *PatchStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchStatusReq.ProtoReflect.Descriptor instead.
func (*PatchStatusReq) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *PatchStatusReq) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *PatchStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PatchStatusReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PatchStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ticket        *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchStatusRes) Reset() {
	*x = PatchStatusRes{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchStatusRes) ProtoMessage() {}

func (x *PatchStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchStatusRes.ProtoReflect.Descriptor instead.
func (*PatchStatusRes) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *PatchStatusRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PatchStatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PatchStatusRes) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type GetTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketReq) Reset() {
	*x = GetTicketReq{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketReq) ProtoMessage() {}

func (x *GetTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketReq.ProtoReflect.Descriptor instead.
func (*GetTicketReq) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *GetTicketReq) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type GetTicketRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ticket        *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRes) Reset() {
	*x = GetTicketRes{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRes) ProtoMessage() {}

func (x *GetTicketRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRes.ProtoReflect.Descriptor instead.
func (*GetTicketRes) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{9}
}

func (x *GetTicketRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTicketRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTicketRes) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type ListTicketsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsReq) Reset() {
	*x = ListTicketsReq{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsReq) ProtoMessage() {}

func (x *ListTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsReq.ProtoReflect.Descriptor instead.
func (*ListTicketsReq) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{10}
}

func (x *ListTicketsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTicketsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTicketsReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListTicketsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*Ticket              `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRes) Reset() {
	*x = ListTicketsRes{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRes) ProtoMessage() {}

func (x *ListTicketsRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRes.ProtoReflect.Descriptor instead.
func (*ListTicketsRes) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{11}
}

func (x *ListTicketsRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListTicketsRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListTicketsRes) GetList() []*Ticket {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTicketsRes) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AfterSequence int64                  `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesReq) Reset() {
	*x = GetMessagesReq{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReq) ProtoMessage() {}

func (x *GetMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReq.ProtoReflect.Descriptor instead.
func (*GetMessagesReq) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{12}
}

func (x *GetMessagesReq) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GetMessagesReq) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *GetMessagesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List              []*TicketMessage       `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	NextAfterSequence int64                  `protobuf:"varint,4,opt,name=next_after_sequence,json=nextAfterSequence,proto3" json:"next_after_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMessagesRes) Reset() {
	*x = GetMessagesRes{}
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRes) ProtoMessage() {}

func (x *GetMessagesRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_ticket_ticket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRes.ProtoReflect.Descriptor instead.
func (*GetMessagesRes) Descriptor() ([]byte, []int) {
	return file_user_v1_ticket_ticket_proto_rawDescGZIP(), []int{13}
}

func (x *GetMessagesRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMessagesRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMessagesRes) GetList() []*TicketMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetMessagesRes) GetNextAfterSequence() int64 {
	if x != nil {
		return x.NextAfterSequence
	}
	return 0
}

var File_user_v1_ticket_ticket_proto protoreflect.FileDescriptor

const file_user_v1_ticket_ticket_proto_rawDesc = "" +
	"\n" +
	"\x1buser/v1/ticket/ticket.proto\x12\x12api.user.v1.ticket\x1a\x1cgoogle/api/annotations.proto\"\x98\x02\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rticket_number\x18\x02 \x01(\x03R\fticketNumber\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12%\n" +
	"\x0eawaiting_actor\x18\x06 \x01(\tR\rawaitingActor\x12*\n" +
	"\x11latest_message_at\x18\a \x01(\x03R\x0flatestMessageAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xb7\x01\n" +
	"\rTicketMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsequence_no\x18\x02 \x01(\x03R\n" +
	"sequenceNo\x12\x1f\n" +
	"\vsender_type\x18\x03 \x01(\tR\n" +
	"senderType\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x17\n" +
	"\asent_at\x18\x06 \x01(\x03R\x06sentAt\"A\n" +
	"\x0fCreateTicketReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xbf\x01\n" +
	"\x0fCreateTicketRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06ticket\x18\x03 \x01(\v2\x1a.api.user.v1.ticket.TicketR\x06ticket\x12D\n" +
	"\fmessage_info\x18\x04 \x01(\v2!.api.user.v1.ticket.TicketMessageR\vmessageInfo\"I\n" +
	"\x10CreateMessageReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8c\x01\n" +
	"\x10CreateMessageRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\fmessage_info\x18\x03 \x01(\v2!.api.user.v1.ticket.TicketMessageR\vmessageInfo\"]\n" +
	"\x0ePatchStatusReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"x\n" +
	"\x0ePatchStatusRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06ticket\x18\x03 \x01(\v2\x1a.api.user.v1.ticket.TicketR\x06ticket\"+\n" +
	"\fGetTicketReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"v\n" +
	"\fGetTicketRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06ticket\x18\x03 \x01(\v2\x1a.api.user.v1.ticket.TicketR\x06ticket\"V\n" +
	"\x0eListTicketsReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x95\x01\n" +
	"\x0eListTicketsRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04list\x18\x03 \x03(\v2\x1a.api.user.v1.ticket.TicketR\x04list\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\"j\n" +
	"\x0eGetMessagesReq\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x03R\rafterSequence\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xab\x01\n" +
	"\x0eGetMessagesRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04list\x18\x03 \x03(\v2!.api.user.v1.ticket.TicketMessageR\x04list\x12.\n" +
	"\x13next_after_sequence\x18\x04 \x01(\x03R\x11nextAfterSequence2\xfa\x05\n" +
	"\rTicketService\x12h\n" +
	"\x04List\x12\".api.user.v1.ticket.ListTicketsReq\x1a\".api.user.v1.ticket.ListTicketsRes\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/user/tickets\x12o\n" +
	"\x03Get\x12 .api.user.v1.ticket.GetTicketReq\x1a .api.user.v1.ticket.GetTicketRes\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/user/tickets/{ticket_id}\x12\x84\x01\n" +
	"\vGetMessages\x12\".api.user.v1.ticket.GetMessagesReq\x1a\".api.user.v1.ticket.GetMessagesRes\"-\x82\xd3\xe4\x93\x02'\x12%/v1/user/tickets/{ticket_id}/messages\x12o\n" +
	"\x06Create\x12#.api.user.v1.ticket.CreateTicketReq\x1a#.api.user.v1.ticket.CreateTicketRes\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/user/tickets\x12\x8d\x01\n" +
	"\rCreateMessage\x12$.api.user.v1.ticket.CreateMessageReq\x1a$.api.user.v1.ticket.CreateMessageRes\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/user/tickets/{ticket_id}/messages\x12\x85\x01\n" +
	"\vPatchStatus\x12\".api.user.v1.ticket.PatchStatusReq\x1a\".api.user.v1.ticket.PatchStatusRes\".\x82\xd3\xe4\x93\x02(:\x01*2#/v1/user/tickets/{ticket_id}/statusB;\n" +
	"\x12api.user.v1.ticketP\x01Z#cwxu-algo/api/user/v1/ticket;ticketb\x06proto3"

var (
	file_user_v1_ticket_ticket_proto_rawDescOnce sync.Once
	file_user_v1_ticket_ticket_proto_rawDescData []byte
)

func file_user_v1_ticket_ticket_proto_rawDescGZIP() []byte {
	file_user_v1_ticket_ticket_proto_rawDescOnce.Do(func() {
		file_user_v1_ticket_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_ticket_ticket_proto_rawDesc), len(file_user_v1_ticket_ticket_proto_rawDesc)))
	})
	return file_user_v1_ticket_ticket_proto_rawDescData
}

var file_user_v1_ticket_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_v1_ticket_ticket_proto_goTypes = []any{
	(*Ticket)(nil),           // 0: api.user.v1.ticket.Ticket
	(*TicketMessage)(nil),    // 1: api.user.v1.ticket.TicketMessage
	(*CreateTicketReq)(nil),  // 2: api.user.v1.ticket.CreateTicketReq
	(*CreateTicketRes)(nil),  // 3: api.user.v1.ticket.CreateTicketRes
	(*CreateMessageReq)(nil), // 4: api.user.v1.ticket.CreateMessageReq
	(*CreateMessageRes)(nil), // 5: api.user.v1.ticket.CreateMessageRes
	(*PatchStatusReq)(nil),   // 6: api.user.v1.ticket.PatchStatusReq
	(*PatchStatusRes)(nil),   // 7: api.user.v1.ticket.PatchStatusRes
	(*GetTicketReq)(nil),     // 8: api.user.v1.ticket.GetTicketReq
	(*GetTicketRes)(nil),     // 9: api.user.v1.ticket.GetTicketRes
	(*ListTicketsReq)(nil),   // 10: api.user.v1.ticket.ListTicketsReq
	(*ListTicketsRes)(nil),   // 11: api.user.v1.ticket.ListTicketsRes
	(*GetMessagesReq)(nil),   // 12: api.user.v1.ticket.GetMessagesReq
	(*GetMessagesRes)(nil),   // 13: api.user.v1.ticket.GetMessagesRes
}
var file_user_v1_ticket_ticket_proto_depIdxs = []int32{
	0,  // 0: api.user.v1.ticket.CreateTicketRes.ticket:type_name -> api.user.v1.ticket.Ticket
	1,  // 1: api.user.v1.ticket.CreateTicketRes.message_info:type_name -> api.user.v1.ticket.TicketMessage
	1,  // 2: api.user.v1.ticket.CreateMessageRes.message_info:type_name -> api.user.v1.ticket.TicketMessage
	0,  // 3: api.user.v1.ticket.PatchStatusRes.ticket:type_name -> api.user.v1.ticket.Ticket
	0,  // 4: api.user.v1.ticket.GetTicketRes.ticket:type_name -> api.user.v1.ticket.Ticket
	0,  // 5: api.user.v1.ticket.ListTicketsRes.list:type_name -> api.user.v1.ticket.Ticket
	1,  // 6: api.user.v1.ticket.GetMessagesRes.list:type_name -> api.user.v1.ticket.TicketMessage
	10, // 7: api.user.v1.ticket.TicketService.List:input_type -> api.user.v1.ticket.ListTicketsReq
	8,  // 8: api.user.v1.ticket.TicketService.Get:input_type -> api.user.v1.ticket.GetTicketReq
	12, // 9: api.user.v1.ticket.TicketService.GetMessages:input_type -> api.user.v1.ticket.GetMessagesReq
	2,  // 10: api.user.v1.ticket.TicketService.Create:input_type -> api.user.v1.ticket.CreateTicketReq
	4,  // 11: api.user.v1.ticket.TicketService.CreateMessage:input_type -> api.user.v1.ticket.CreateMessageReq
	6,  // 12: api.user.v1.ticket.TicketService.PatchStatus:input_type -> api.user.v1.ticket.PatchStatusReq
	11, // 13: api.user.v1.ticket.TicketService.List:output_type -> api.user.v1.ticket.ListTicketsRes
	9,  // 14: api.user.v1.ticket.TicketService.Get:output_type -> api.user.v1.ticket.GetTicketRes
	13, // 15: api.user.v1.ticket.TicketService.GetMessages:output_type -> api.user.v1.ticket.GetMessagesRes
	3,  // 16: api.user.v1.ticket.TicketService.Create:output_type -> api.user.v1.ticket.CreateTicketRes
	5,  // 17: api.user.v1.ticket.TicketService.CreateMessage:output_type -> api.user.v1.ticket.CreateMessageRes
	7,  // 18: api.user.v1.ticket.TicketService.PatchStatus:output_type -> api.user.v1.ticket.PatchStatusRes
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_v1_ticket_ticket_proto_init() }
func file_user_v1_ticket_ticket_proto_init() {
	if File_user_v1_ticket_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_ticket_ticket_proto_rawDesc), len(file_user_v1_ticket_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_ticket_ticket_proto_goTypes,
		DependencyIndexes: file_user_v1_ticket_ticket_proto_depIdxs,
		MessageInfos:      file_user_v1_ticket_ticket_proto_msgTypes,
	}.Build()
	File_user_v1_ticket_ticket_proto = out.File
	file_user_v1_ticket_ticket_proto_goTypes = nil
	file_user_v1_ticket_ticket_proto_depIdxs = nil
}
