// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: user/v1/role/role.proto

package role

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRoleList = "/api.user.v1.role.Role/List"
const OperationRoleSetUserRole = "/api.user.v1.role.Role/SetUserRole"

type RoleHTTPServer interface {
	// List 获取所有角色列表（所有人可访问）
	List(context.Context, *ListReq) (*ListRes, error)
	// SetUserRole 设置用户角色（仅管理员可调用）
	SetUserRole(context.Context, *SetUserRoleReq) (*SetUserRoleRes, error)
}

func RegisterRoleHTTPServer(s *http.Server, srv RoleHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/user/role/list", _Role_List3_HTTP_Handler(srv))
	r.POST("/v1/user/role/set-user-role", _Role_SetUserRole0_HTTP_Handler(srv))
}

func _Role_List3_HTTP_Handler(srv RoleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRes)
		return ctx.Result(200, reply)
	}
}

func _Role_SetUserRole0_HTTP_Handler(srv RoleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetUserRoleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleSetUserRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetUserRole(ctx, req.(*SetUserRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetUserRoleRes)
		return ctx.Result(200, reply)
	}
}

type RoleHTTPClient interface {
	// List 获取所有角色列表（所有人可访问）
	List(ctx context.Context, req *ListReq, opts ...http.CallOption) (rsp *ListRes, err error)
	// SetUserRole 设置用户角色（仅管理员可调用）
	SetUserRole(ctx context.Context, req *SetUserRoleReq, opts ...http.CallOption) (rsp *SetUserRoleRes, err error)
}

type RoleHTTPClientImpl struct {
	cc *http.Client
}

func NewRoleHTTPClient(client *http.Client) RoleHTTPClient {
	return &RoleHTTPClientImpl{client}
}

// List 获取所有角色列表（所有人可访问）
func (c *RoleHTTPClientImpl) List(ctx context.Context, in *ListReq, opts ...http.CallOption) (*ListRes, error) {
	var out ListRes
	pattern := "/v1/user/role/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoleList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetUserRole 设置用户角色（仅管理员可调用）
func (c *RoleHTTPClientImpl) SetUserRole(ctx context.Context, in *SetUserRoleReq, opts ...http.CallOption) (*SetUserRoleRes, error) {
	var out SetUserRoleRes
	pattern := "/v1/user/role/set-user-role"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoleSetUserRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
