// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: core/v1/contest_calendar/calendar.proto

package contest_calendar

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalendarItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformName  string                 `protobuf:"bytes,3,opt,name=platformName,proto3" json:"platformName,omitempty"`
	ExternalId    string                 `protobuf:"bytes,4,opt,name=externalId,proto3" json:"externalId,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,8,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	IconUrl       string                 `protobuf:"bytes,10,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	Subscribed    bool                   `protobuf:"varint,11,opt,name=subscribed,proto3" json:"subscribed,omitempty"` // 当前用户是否有该场或平台级订阅（需登录上下文时填充）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarItem) Reset() {
	*x = CalendarItem{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarItem) ProtoMessage() {}

func (x *CalendarItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarItem.ProtoReflect.Descriptor instead.
func (*CalendarItem) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CalendarItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CalendarItem) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *CalendarItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CalendarItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CalendarItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CalendarItem) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CalendarItem) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CalendarItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CalendarItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CalendarItem) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

type ListCalendarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // upcoming | ongoing | ended | all
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	TimeFrom      int64                  `protobuf:"varint,6,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"` // 开赛时间下界（unix 秒，含，0=不限）
	TimeTo        int64                  `protobuf:"varint,7,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`       // 开赛时间上界（unix 秒，含，0=不限）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCalendarReq) Reset() {
	*x = ListCalendarReq{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCalendarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCalendarReq) ProtoMessage() {}

func (x *ListCalendarReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCalendarReq.ProtoReflect.Descriptor instead.
func (*ListCalendarReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *ListCalendarReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListCalendarReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListCalendarReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCalendarReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCalendarReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCalendarReq) GetTimeFrom() int64 {
	if x != nil {
		return x.TimeFrom
	}
	return 0
}

func (x *ListCalendarReq) GetTimeTo() int64 {
	if x != nil {
		return x.TimeTo
	}
	return 0
}

type ListCalendarRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CalendarItem        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCalendarRes) Reset() {
	*x = ListCalendarRes{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCalendarRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCalendarRes) ProtoMessage() {}

func (x *ListCalendarRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCalendarRes.ProtoReflect.Descriptor instead.
func (*ListCalendarRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *ListCalendarRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListCalendarRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListCalendarRes) GetData() []*CalendarItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListCalendarRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PlatformItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformName  string                 `protobuf:"bytes,2,opt,name=platformName,proto3" json:"platformName,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformItem) Reset() {
	*x = PlatformItem{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformItem) ProtoMessage() {}

func (x *PlatformItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformItem.ProtoReflect.Descriptor instead.
func (*PlatformItem) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *PlatformItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformItem) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *PlatformItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PlatformItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListPlatformsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpcomingOnly  bool                   `protobuf:"varint,1,opt,name=upcomingOnly,proto3" json:"upcomingOnly,omitempty"` // 默认 true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformsReq) Reset() {
	*x = ListPlatformsReq{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformsReq) ProtoMessage() {}

func (x *ListPlatformsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformsReq.ProtoReflect.Descriptor instead.
func (*ListPlatformsReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlatformsReq) GetUpcomingOnly() bool {
	if x != nil {
		return x.UpcomingOnly
	}
	return false
}

type ListPlatformsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*PlatformItem        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformsRes) Reset() {
	*x = ListPlatformsRes{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformsRes) ProtoMessage() {}

func (x *ListPlatformsRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformsRes.ProtoReflect.Descriptor instead.
func (*ListPlatformsRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlatformsRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPlatformsRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListPlatformsRes) GetData() []*PlatformItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope          string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // platform | contest
	Platform       string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	CalendarId     uint32                 `protobuf:"varint,4,opt,name=calendarId,proto3" json:"calendarId,omitempty"`
	AdvanceMinutes int32                  `protobuf:"varint,5,opt,name=advanceMinutes,proto3" json:"advanceMinutes,omitempty"`
	Enabled        bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ContestName    string                 `protobuf:"bytes,7,opt,name=contestName,proto3" json:"contestName,omitempty"` // contest 订阅时回填
	ContestUrl     string                 `protobuf:"bytes,8,opt,name=contestUrl,proto3" json:"contestUrl,omitempty"`
	StartTime      int64                  `protobuf:"varint,9,opt,name=startTime,proto3" json:"startTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubItem) Reset() {
	*x = SubItem{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubItem) ProtoMessage() {}

func (x *SubItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubItem.ProtoReflect.Descriptor instead.
func (*SubItem) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{6}
}

func (x *SubItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubItem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SubItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SubItem) GetCalendarId() uint32 {
	if x != nil {
		return x.CalendarId
	}
	return 0
}

func (x *SubItem) GetAdvanceMinutes() int32 {
	if x != nil {
		return x.AdvanceMinutes
	}
	return 0
}

func (x *SubItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SubItem) GetContestName() string {
	if x != nil {
		return x.ContestName
	}
	return ""
}

func (x *SubItem) GetContestUrl() string {
	if x != nil {
		return x.ContestUrl
	}
	return ""
}

func (x *SubItem) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type GetMySubsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubsReq) Reset() {
	*x = GetMySubsReq{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubsReq) ProtoMessage() {}

func (x *GetMySubsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubsReq.ProtoReflect.Descriptor instead.
func (*GetMySubsReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{7}
}

type GetMySubsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SubItem             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubsRes) Reset() {
	*x = GetMySubsRes{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubsRes) ProtoMessage() {}

func (x *GetMySubsRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubsRes.ProtoReflect.Descriptor instead.
func (*GetMySubsRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{8}
}

func (x *GetMySubsRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMySubsRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMySubsRes) GetData() []*SubItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpsertSubReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`                    // platform | contest
	Platform       string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`              // platform 订阅必填；contest 可省略（服务端从日历补）
	CalendarId     uint32                 `protobuf:"varint,3,opt,name=calendarId,proto3" json:"calendarId,omitempty"`         // contest 订阅必填
	AdvanceMinutes int32                  `protobuf:"varint,4,opt,name=advanceMinutes,proto3" json:"advanceMinutes,omitempty"` // 白名单分钟
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertSubReq) Reset() {
	*x = UpsertSubReq{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSubReq) ProtoMessage() {}

func (x *UpsertSubReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSubReq.ProtoReflect.Descriptor instead.
func (*UpsertSubReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertSubReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *UpsertSubReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpsertSubReq) GetCalendarId() uint32 {
	if x != nil {
		return x.CalendarId
	}
	return 0
}

func (x *UpsertSubReq) GetAdvanceMinutes() int32 {
	if x != nil {
		return x.AdvanceMinutes
	}
	return 0
}

func (x *UpsertSubReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpsertSubRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SubItem               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSubRes) Reset() {
	*x = UpsertSubRes{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSubRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSubRes) ProtoMessage() {}

func (x *UpsertSubRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSubRes.ProtoReflect.Descriptor instead.
func (*UpsertSubRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertSubRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpsertSubRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertSubRes) GetData() *SubItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteSubReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	CalendarId    uint32                 `protobuf:"varint,3,opt,name=calendarId,proto3" json:"calendarId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubReq) Reset() {
	*x = DeleteSubReq{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubReq) ProtoMessage() {}

func (x *DeleteSubReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubReq.ProtoReflect.Descriptor instead.
func (*DeleteSubReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSubReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DeleteSubReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeleteSubReq) GetCalendarId() uint32 {
	if x != nil {
		return x.CalendarId
	}
	return 0
}

type DeleteSubRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubRes) Reset() {
	*x = DeleteSubRes{}
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubRes) ProtoMessage() {}

func (x *DeleteSubRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_calendar_calendar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubRes.ProtoReflect.Descriptor instead.
func (*DeleteSubRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_calendar_calendar_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSubRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteSubRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_core_v1_contest_calendar_calendar_proto protoreflect.FileDescriptor

const file_core_v1_contest_calendar_calendar_proto_rawDesc = "" +
	"\n" +
	"'core/v1/contest_calendar/calendar.proto\x12\x1capi.core.v1.contest_calendar\x1a\x1cgoogle/api/annotations.proto\"\xae\x02\n" +
	"\fCalendarItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\"\n" +
	"\fplatformName\x18\x03 \x01(\tR\fplatformName\x12\x1e\n" +
	"\n" +
	"externalId\x18\x04 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\x03R\aendTime\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x18\n" +
	"\aiconUrl\x18\n" +
	" \x01(\tR\aiconUrl\x12\x1e\n" +
	"\n" +
	"subscribed\x18\v \x01(\bR\n" +
	"subscribed\"\xc3\x01\n" +
	"\x0fListCalendarReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x1b\n" +
	"\ttime_from\x18\x06 \x01(\x03R\btimeFrom\x12\x17\n" +
	"\atime_to\x18\a \x01(\x03R\x06timeTo\"\x95\x01\n" +
	"\x0fListCalendarRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x03(\v2*.api.core.v1.contest_calendar.CalendarItemR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"~\n" +
	"\fPlatformItem\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\"\n" +
	"\fplatformName\x18\x02 \x01(\tR\fplatformName\x12\x18\n" +
	"\aiconUrl\x18\x03 \x01(\tR\aiconUrl\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"6\n" +
	"\x10ListPlatformsReq\x12\"\n" +
	"\fupcomingOnly\x18\x01 \x01(\bR\fupcomingOnly\"\x80\x01\n" +
	"\x10ListPlatformsRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x03(\v2*.api.core.v1.contest_calendar.PlatformItemR\x04data\"\x8d\x02\n" +
	"\aSubItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"calendarId\x18\x04 \x01(\rR\n" +
	"calendarId\x12&\n" +
	"\x0eadvanceMinutes\x18\x05 \x01(\x05R\x0eadvanceMinutes\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12 \n" +
	"\vcontestName\x18\a \x01(\tR\vcontestName\x12\x1e\n" +
	"\n" +
	"contestUrl\x18\b \x01(\tR\n" +
	"contestUrl\x12\x1c\n" +
	"\tstartTime\x18\t \x01(\x03R\tstartTime\"\x0e\n" +
	"\fGetMySubsReq\"w\n" +
	"\fGetMySubsRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.api.core.v1.contest_calendar.SubItemR\x04data\"\xa2\x01\n" +
	"\fUpsertSubReq\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"calendarId\x18\x03 \x01(\rR\n" +
	"calendarId\x12&\n" +
	"\x0eadvanceMinutes\x18\x04 \x01(\x05R\x0eadvanceMinutes\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"w\n" +
	"\fUpsertSubRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.api.core.v1.contest_calendar.SubItemR\x04data\"`\n" +
	"\fDeleteSubReq\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"calendarId\x18\x03 \x01(\rR\n" +
	"calendarId\"<\n" +
	"\fDeleteSubRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfb\x05\n" +
	"\x0fContestCalendar\x12\x94\x01\n" +
	"\fListCalendar\x12-.api.core.v1.contest_calendar.ListCalendarReq\x1a-.api.core.v1.contest_calendar.ListCalendarRes\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/core/contest-calendar/list\x12\x9c\x01\n" +
	"\rListPlatforms\x12..api.core.v1.contest_calendar.ListPlatformsReq\x1a..api.core.v1.contest_calendar.ListPlatformsRes\"+\x82\xd3\xe4\x93\x02%\x12#/v1/core/contest-calendar/platforms\x12\x8a\x01\n" +
	"\tGetMySubs\x12*.api.core.v1.contest_calendar.GetMySubsReq\x1a*.api.core.v1.contest_calendar.GetMySubsRes\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/core/contest-calendar/sub\x12\x8d\x01\n" +
	"\tUpsertSub\x12*.api.core.v1.contest_calendar.UpsertSubReq\x1a*.api.core.v1.contest_calendar.UpsertSubRes\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/core/contest-calendar/sub\x12\x94\x01\n" +
	"\tDeleteSub\x12*.api.core.v1.contest_calendar.DeleteSubReq\x1a*.api.core.v1.contest_calendar.DeleteSubRes\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/core/contest-calendar/sub/deleteBY\n" +
	"\x1capi.core.v1.contest_calendarP\x01Z7cwxu-algo/api/core/v1/contest_calendar;contest_calendarb\x06proto3"

var (
	file_core_v1_contest_calendar_calendar_proto_rawDescOnce sync.Once
	file_core_v1_contest_calendar_calendar_proto_rawDescData []byte
)

func file_core_v1_contest_calendar_calendar_proto_rawDescGZIP() []byte {
	file_core_v1_contest_calendar_calendar_proto_rawDescOnce.Do(func() {
		file_core_v1_contest_calendar_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_contest_calendar_calendar_proto_rawDesc), len(file_core_v1_contest_calendar_calendar_proto_rawDesc)))
	})
	return file_core_v1_contest_calendar_calendar_proto_rawDescData
}

var file_core_v1_contest_calendar_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_v1_contest_calendar_calendar_proto_goTypes = []any{
	(*CalendarItem)(nil),     // 0: api.core.v1.contest_calendar.CalendarItem
	(*ListCalendarReq)(nil),  // 1: api.core.v1.contest_calendar.ListCalendarReq
	(*ListCalendarRes)(nil),  // 2: api.core.v1.contest_calendar.ListCalendarRes
	(*PlatformItem)(nil),     // 3: api.core.v1.contest_calendar.PlatformItem
	(*ListPlatformsReq)(nil), // 4: api.core.v1.contest_calendar.ListPlatformsReq
	(*ListPlatformsRes)(nil), // 5: api.core.v1.contest_calendar.ListPlatformsRes
	(*SubItem)(nil),          // 6: api.core.v1.contest_calendar.SubItem
	(*GetMySubsReq)(nil),     // 7: api.core.v1.contest_calendar.GetMySubsReq
	(*GetMySubsRes)(nil),     // 8: api.core.v1.contest_calendar.GetMySubsRes
	(*UpsertSubReq)(nil),     // 9: api.core.v1.contest_calendar.UpsertSubReq
	(*UpsertSubRes)(nil),     // 10: api.core.v1.contest_calendar.UpsertSubRes
	(*DeleteSubReq)(nil),     // 11: api.core.v1.contest_calendar.DeleteSubReq
	(*DeleteSubRes)(nil),     // 12: api.core.v1.contest_calendar.DeleteSubRes
}
var file_core_v1_contest_calendar_calendar_proto_depIdxs = []int32{
	0,  // 0: api.core.v1.contest_calendar.ListCalendarRes.data:type_name -> api.core.v1.contest_calendar.CalendarItem
	3,  // 1: api.core.v1.contest_calendar.ListPlatformsRes.data:type_name -> api.core.v1.contest_calendar.PlatformItem
	6,  // 2: api.core.v1.contest_calendar.GetMySubsRes.data:type_name -> api.core.v1.contest_calendar.SubItem
	6,  // 3: api.core.v1.contest_calendar.UpsertSubRes.data:type_name -> api.core.v1.contest_calendar.SubItem
	1,  // 4: api.core.v1.contest_calendar.ContestCalendar.ListCalendar:input_type -> api.core.v1.contest_calendar.ListCalendarReq
	4,  // 5: api.core.v1.contest_calendar.ContestCalendar.ListPlatforms:input_type -> api.core.v1.contest_calendar.ListPlatformsReq
	7,  // 6: api.core.v1.contest_calendar.ContestCalendar.GetMySubs:input_type -> api.core.v1.contest_calendar.GetMySubsReq
	9,  // 7: api.core.v1.contest_calendar.ContestCalendar.UpsertSub:input_type -> api.core.v1.contest_calendar.UpsertSubReq
	11, // 8: api.core.v1.contest_calendar.ContestCalendar.DeleteSub:input_type -> api.core.v1.contest_calendar.DeleteSubReq
	2,  // 9: api.core.v1.contest_calendar.ContestCalendar.ListCalendar:output_type -> api.core.v1.contest_calendar.ListCalendarRes
	5,  // 10: api.core.v1.contest_calendar.ContestCalendar.ListPlatforms:output_type -> api.core.v1.contest_calendar.ListPlatformsRes
	8,  // 11: api.core.v1.contest_calendar.ContestCalendar.GetMySubs:output_type -> api.core.v1.contest_calendar.GetMySubsRes
	10, // 12: api.core.v1.contest_calendar.ContestCalendar.UpsertSub:output_type -> api.core.v1.contest_calendar.UpsertSubRes
	12, // 13: api.core.v1.contest_calendar.ContestCalendar.DeleteSub:output_type -> api.core.v1.contest_calendar.DeleteSubRes
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_core_v1_contest_calendar_calendar_proto_init() }
func file_core_v1_contest_calendar_calendar_proto_init() {
	if File_core_v1_contest_calendar_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_contest_calendar_calendar_proto_rawDesc), len(file_core_v1_contest_calendar_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_contest_calendar_calendar_proto_goTypes,
		DependencyIndexes: file_core_v1_contest_calendar_calendar_proto_depIdxs,
		MessageInfos:      file_core_v1_contest_calendar_calendar_proto_msgTypes,
	}.Build()
	File_core_v1_contest_calendar_calendar_proto = out.File
	file_core_v1_contest_calendar_calendar_proto_goTypes = nil
	file_core_v1_contest_calendar_calendar_proto_depIdxs = nil
}
