// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cwxu-algo/app/common/conf"
	"cwxu-algo/app/common/discovery"
	"cwxu-algo/app/user/internal/biz"
	"cwxu-algo/app/user/internal/data"
	"cwxu-algo/app/user/internal/data/dal"
	"cwxu-algo/app/user/internal/server"
	"cwxu-algo/app/user/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gorm.io/gorm"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, supportCenter *conf.SupportCenter, legacySiteConfig data.LegacySiteConfig) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, legacySiteConfig)
	if err != nil {
		return nil, nil, err
	}
	profileDal := dal.NewProfileDal(dataData)
	register := discovery.NewConsulRegister(confServer)
	profileUseCase := biz.NewProfileUseCase(profileDal)
	profileService := service.NewProfileService(profileDal, register, profileUseCase, dataData)
	subscriptionDal := dal.NewSubscriptionDal(dataData)
	subscriptionService := service.NewSubscriptionService(dataData, subscriptionDal, profileDal)
	luoguPluginService := service.NewLuoguPluginService(dataData)
	grpcServer := server.NewGRPCServer(confServer, logger, profileService, subscriptionService, luoguPluginService)
	authService := service.NewAuthService(dataData, register)
	groupDal := dal.NewGroupDal(dataData)
	groupUseCase := biz.NewGroupUseCase(groupDal)
	groupService := service.NewGroupService(register, groupUseCase, groupDal)
	roleService := service.NewRoleService(profileDal)
	siteService := service.NewSiteService(dataData)
	orgService := service.NewOrgService(dataData)
	rbacService := service.NewRbacService(dataData)
	pasteService := service.NewPasteService(dataData)
	socialService := service.NewSocialService(dataData)
	notificationService := service.NewNotificationService(dataData)
	blogService := service.NewBlogService(dataData)
	seoService := service.NewSEOService(dataData)
	db := provideUserDB(dataData)
	ticketService := service.NewTicketService(supportCenter, db)
	httpServer := server.NewHTTPServer(confServer, dataData, authService, profileService, groupService, roleService, siteService, orgService, rbacService, pasteService, socialService, notificationService, blogService, seoService, subscriptionService, ticketService, luoguPluginService, logger)
	app := newApp(logger, grpcServer, httpServer, register)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// provideUserDB 供需要直接访问 gorm.DB 的 provider（如工单服务）使用。
func provideUserDB(d *data.Data) *gorm.DB {
	return d.DB
}
