// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user/v1/auth/auth.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名或邮箱
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	JwtToken string                 `protobuf:"bytes,2,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	// 登录前处于休眠（不活跃）；已触发全量同步
	WasDormant bool `protobuf:"varint,4,opt,name=was_dormant,json=wasDormant,proto3" json:"was_dormant,omitempty"`
	// 是否已为该用户入队全量爬虫
	SyncStarted bool `protobuf:"varint,5,opt,name=sync_started,json=syncStarted,proto3" json:"sync_started,omitempty"`
	// 距上次活跃的整天数（登录前计算；从未记录则按注册时间）
	InactiveDays  int32 `protobuf:"varint,6,opt,name=inactive_days,json=inactiveDays,proto3" json:"inactive_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginRes) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *LoginRes) GetWasDormant() bool {
	if x != nil {
		return x.WasDormant
	}
	return false
}

func (x *LoginRes) GetSyncStarted() bool {
	if x != nil {
		return x.SyncStarted
	}
	return false
}

func (x *LoginRes) GetInactiveDays() int32 {
	if x != nil {
		return x.InactiveDays
	}
	return 0
}

type RegisterReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email    string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	GroupId  int64                  `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 邮箱验证码
	Code string `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	// 可选：组织邀请识别码；注册成功后自动加入该组织（自动通过则设为默认组织）
	InviteCode    string `protobuf:"bytes,7,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterReq) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshReq) Reset() {
	*x = RefreshReq{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshReq) ProtoMessage() {}

func (x *RefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshReq.ProtoReflect.Descriptor instead.
func (*RefreshReq) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{4}
}

// purpose: register | reset | change_email
type SendCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeReq) Reset() {
	*x = SendCodeReq{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeReq) ProtoMessage() {}

func (x *SendCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeReq.ProtoReflect.Descriptor instead.
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SendCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendCodeReq) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type SendCodeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeRes) Reset() {
	*x = SendCodeRes{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeRes) ProtoMessage() {}

func (x *SendCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeRes.ProtoReflect.Descriptor instead.
func (*SendCodeRes) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SendCodeRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendCodeRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetPasswordReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 新密码（客户端 SHA256 后传输）
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ResetPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResetPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRes) Reset() {
	*x = ResetPasswordRes{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRes) ProtoMessage() {}

func (x *ResetPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRes.ProtoReflect.Descriptor instead.
func (*ResetPasswordRes) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ResetPasswordRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 客户端 SHA256 后传输
type ChangePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRes) Reset() {
	*x = ChangePasswordRes{}
	mi := &file_user_v1_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRes) ProtoMessage() {}

func (x *ChangePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRes.ProtoReflect.Descriptor instead.
func (*ChangePasswordRes) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePasswordRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangePasswordRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_v1_auth_auth_proto protoreflect.FileDescriptor

const file_user_v1_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x17user/v1/auth/auth.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xc3\x01\n" +
	"\bLoginRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bjwtToken\x18\x02 \x01(\tR\bjwtToken\x12\x1f\n" +
	"\vwas_dormant\x18\x04 \x01(\bR\n" +
	"wasDormant\x12!\n" +
	"\fsync_started\x18\x05 \x01(\bR\vsyncStarted\x12#\n" +
	"\rinactive_days\x18\x06 \x01(\x05R\finactiveDays\"\xbd\x01\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"inviteCode\x18\a \x01(\tR\n" +
	"inviteCode\"A\n" +
	"\vRegisterRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\f\n" +
	"\n" +
	"RefreshReq\"=\n" +
	"\vSendCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\"A\n" +
	"\vSendCodeRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x10ResetPasswordReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"F\n" +
	"\x10ResetPasswordRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x11ChangePasswordReq\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"G\n" +
	"\x11ChangePasswordRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf5\x04\n" +
	"\x04Auth\x12U\n" +
	"\x05Login\x12\x15.api.user.v1.LoginReq\x1a\x15.api.user.v1.LoginRes\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/user/auth/login\x12a\n" +
	"\bRegister\x12\x18.api.user.v1.RegisterReq\x1a\x18.api.user.v1.RegisterRes\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/user/auth/register\x12[\n" +
	"\aRefresh\x12\x17.api.user.v1.RefreshReq\x1a\x15.api.user.v1.LoginRes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/user/auth/refresh\x12b\n" +
	"\bSendCode\x12\x18.api.user.v1.SendCodeReq\x1a\x18.api.user.v1.SendCodeRes\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/user/auth/send-code\x12v\n" +
	"\rResetPassword\x12\x1d.api.user.v1.ResetPasswordReq\x1a\x1d.api.user.v1.ResetPasswordRes\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/user/auth/reset-password\x12z\n" +
	"\x0eChangePassword\x12\x1e.api.user.v1.ChangePasswordReq\x1a\x1e.api.user.v1.ChangePasswordRes\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/user/auth/change-passwordB0\n" +
	"\vapi.user.v1P\x01Z\x1fcwxu-algo/api/user/v1/auth;authb\x06proto3"

var (
	file_user_v1_auth_auth_proto_rawDescOnce sync.Once
	file_user_v1_auth_auth_proto_rawDescData []byte
)

func file_user_v1_auth_auth_proto_rawDescGZIP() []byte {
	file_user_v1_auth_auth_proto_rawDescOnce.Do(func() {
		file_user_v1_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_auth_auth_proto_rawDesc), len(file_user_v1_auth_auth_proto_rawDesc)))
	})
	return file_user_v1_auth_auth_proto_rawDescData
}

var file_user_v1_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_v1_auth_auth_proto_goTypes = []any{
	(*LoginReq)(nil),          // 0: api.user.v1.LoginReq
	(*LoginRes)(nil),          // 1: api.user.v1.LoginRes
	(*RegisterReq)(nil),       // 2: api.user.v1.RegisterReq
	(*RegisterRes)(nil),       // 3: api.user.v1.RegisterRes
	(*RefreshReq)(nil),        // 4: api.user.v1.RefreshReq
	(*SendCodeReq)(nil),       // 5: api.user.v1.SendCodeReq
	(*SendCodeRes)(nil),       // 6: api.user.v1.SendCodeRes
	(*ResetPasswordReq)(nil),  // 7: api.user.v1.ResetPasswordReq
	(*ResetPasswordRes)(nil),  // 8: api.user.v1.ResetPasswordRes
	(*ChangePasswordReq)(nil), // 9: api.user.v1.ChangePasswordReq
	(*ChangePasswordRes)(nil), // 10: api.user.v1.ChangePasswordRes
}
var file_user_v1_auth_auth_proto_depIdxs = []int32{
	0,  // 0: api.user.v1.Auth.Login:input_type -> api.user.v1.LoginReq
	2,  // 1: api.user.v1.Auth.Register:input_type -> api.user.v1.RegisterReq
	4,  // 2: api.user.v1.Auth.Refresh:input_type -> api.user.v1.RefreshReq
	5,  // 3: api.user.v1.Auth.SendCode:input_type -> api.user.v1.SendCodeReq
	7,  // 4: api.user.v1.Auth.ResetPassword:input_type -> api.user.v1.ResetPasswordReq
	9,  // 5: api.user.v1.Auth.ChangePassword:input_type -> api.user.v1.ChangePasswordReq
	1,  // 6: api.user.v1.Auth.Login:output_type -> api.user.v1.LoginRes
	3,  // 7: api.user.v1.Auth.Register:output_type -> api.user.v1.RegisterRes
	1,  // 8: api.user.v1.Auth.Refresh:output_type -> api.user.v1.LoginRes
	6,  // 9: api.user.v1.Auth.SendCode:output_type -> api.user.v1.SendCodeRes
	8,  // 10: api.user.v1.Auth.ResetPassword:output_type -> api.user.v1.ResetPasswordRes
	10, // 11: api.user.v1.Auth.ChangePassword:output_type -> api.user.v1.ChangePasswordRes
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_auth_auth_proto_init() }
func file_user_v1_auth_auth_proto_init() {
	if File_user_v1_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_auth_auth_proto_rawDesc), len(file_user_v1_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_auth_auth_proto_goTypes,
		DependencyIndexes: file_user_v1_auth_auth_proto_depIdxs,
		MessageInfos:      file_user_v1_auth_auth_proto_msgTypes,
	}.Build()
	File_user_v1_auth_auth_proto = out.File
	file_user_v1_auth_auth_proto_goTypes = nil
	file_user_v1_auth_auth_proto_depIdxs = nil
}
